Allow to replace the default contains function.
qooxdoo/qooxdoo pull request #10016
Opened 2020-07-24 14:49 UTC by adrelino

This is just a tiny non-breaking addition to the API, but I consider it very useful.

With the freedom to supply my own contains function to the qx.ui.popup.Manager, I was finally able to fix some issues with too early closing of a parent popup when clicking inside a nested menu.

This allows e.g. to write a custom contains function that not only considers the layout parents, but also logical parents. 

- I needed it to display a table inside a popup withouth the popup closing when (de)-selecting columns from the table-column-menu.
- for my custom select boxes with search capabilities, closing using the _onBlur event of the selectBox was really hard to get right, since a click into the search filter would close the selectBox. I tried lots of workarounds, but with the notion of logical parents this got a whole lot easier.

2020-07-24 15:26 UTC, oetiker approved these changes
that searchable selectbox also sounds very nice :) care to contribute? I am about to write one too ...

2020-07-24 15:27 UTC, derrell approved these changes

2020-07-24 15:29 UTC, cboulanger approved these changes

2020-07-24 16:12 UTC, hkollmann requested changes
What's about using a property instead of the setMethod?
With your solution you can not revert to the old contains function clearly.

2020-07-24 16:21 UTC, adrelino commented
> that searchable selectbox also sounds very nice :) care to contribute? I am about to write one too ...

They are here: https://github.com/adrelino/qooxdoo-extensions. Look for FilterSelectBox, FilterMultiSelectBox, FilterTreeSelectBox. 

The demo is currently hosted at http://www.adrian-haarbach.de/qooxdoo-extensions/build/. Once I know how to fix https://github.com/adrelino/qooxdoo-extensions/issues/1 it should also show up in https://qooxdoo.org/qxl.packagebrowser.

2020-07-24 16:45 UTC, adrelino commented
> What's about using a property instead of the setMethod?
> With your solution you can not revert to the old contains function clearly.

sure, I now changed it to use a property instead.

2020-07-24 20:01 UTC, level420 approved these changes

2020-07-25 13:44 UTC, hkollmann approved these changes
Great!

2020-07-25 13:45 UTC, merged