Add support for sameSite property
qooxdoo/qooxdoo pull request #10011
Opened 2020-07-02 08:07 UTC by oetiker

Hmm, the set cookie method is aiming to become the one with the most attributes.

as reported by @rixs on gitter

2020-07-02 08:13 UTC, cboulanger approved these changes

2020-07-02 19:56 UTC, hkollmann approved these changes

2020-07-02 20:26 UTC, level420 approved these changes

2020-07-03 14:14 UTC, derrell requested changes

2020-07-04 10:06 UTC, oetiker commented on framework/source/class/qx/bom/Cookie.js
> +        cookie.push(";sameSite=", sameSite);
since validation happens at runtime, I see not much of a difference vs the browser complaining if it is unhappy.

2020-07-04 13:08 UTC, derrell approved these changes

2020-07-23 14:08 UTC, johnspackman approved these changes

2020-07-24 10:18 UTC, merged