Local variable gaps is in the wrong scope.
qooxdoo/qooxdoo pull request #10041
Opened 2020-09-21 20:54 UTC by lucapivato

2020-09-22 06:53 UTC, cboulanger approved these changes

2020-09-22 07:48 UTC, oetiker approved these changes
also note as far as `var` is concerned, there is no scope there ... so this change does not change anything afaik

2020-09-22 07:48 UTC, oetiker commented on framework/source/class/qx/ui/layout/HBox.js
> +      var spacing = this.getSpacing(), gaps;
```suggestion
      var spacing = this.getSpacing();
      var gaps;
```

2020-09-22 08:41 UTC, level420 requested changes
Even if var has no local scope, and both versions are equivalent, this code is clearer.
But please change it to what @oetiger suggested and put `var gaps;` in a separate line. Thank you!

2020-09-22 17:36 UTC, hkollmann approved these changes
After changes @oetiker suggested

2020-09-29 13:42 UTC, level420 commented
@lucapivato sorry. I've highjacked your PR and changed the declaration of gaps to a separate line.

2020-09-29 13:45 UTC, level420 approved these changes

2020-09-29 17:10 UTC, derrell approved these changes

2020-09-29 17:29 UTC, merged