Make cookies use SameSite=Strict by default
qooxdoo/qooxdoo pull request #10085
Opened 2021-01-16 11:14 UTC by johnspackman

fixes https://github.com/qooxdoo/qooxdoo/issues/10050

2021-01-16 12:05 UTC, cboulanger approved these changes

2021-01-16 13:27 UTC, derrell requested changes
LGTM, but let's also add this to the non-BC list for release notes, per recent discussion, as part of this PR

2021-01-16 14:39 UTC, derrell approved these changes
Thanks!

2021-01-16 17:01 UTC, hkollmann approved these changes

2021-01-16 22:03 UTC, level420 approved these changes

2021-01-18 13:06 UTC, oetiker approved these changes

2021-01-18 14:18 UTC, merged

2021-01-18 14:19 UTC, cboulanger commented
Thank you @johnspackman !