A more verbose explanation of alias and include keys of appearance selector properties
qooxdoo/qooxdoo pull request #10129
Opened 2021-02-13 16:12 UTC by voger

This PR is an attempt to make a more verbose explanation of the difference between the `include` and `alias` keys of a selector property. Also it replaces the example of `spinner/button` with that of a window so it is easier to show visually the results of the keys.

2021-02-13 17:03 UTC, derrell requested changes
Much more clear. Thanks!

2021-02-13 17:03 UTC, derrell commented on docs/desktop/gui/appearance.md
> +data. Includes may also used standalone without the `style` key but this is
may also BE used standalone

2021-02-13 17:08 UTC, voger commented on docs/desktop/gui/appearance.md
> +data. Includes may also used standalone without the `style` key but this is
Fixed

2021-02-13 17:10 UTC, derrell approved these changes

2021-02-13 18:31 UTC, hkollmann approved these changes

2021-02-13 19:07 UTC, cboulanger approved these changes

2021-02-14 08:33 UTC, level420 approved these changes

2021-02-15 07:30 UTC, rommni commented
Thank you, really much more clear, before today i was still using all of these things without totally understood how it works. I think I will have to clean my code a little now :)

2021-02-15 09:07 UTC, cboulanger commented
4 approvals (2 are necessary for doc changes), merging. Thank you @voger ! It would be great if you could also "backport" the change to the V6 docs at https://github.com/qooxdoo/documentation/tree/gh-pages/6.0 - thank you!

2021-02-15 09:07 UTC, merged

2021-02-15 16:49 UTC, voger commented
@cboulanger sure but how do I do that? Should I clone that repo too and add the changes there also?

2021-02-15 16:52 UTC, cboulanger commented
Yes, that's the fastest way at the moment - unfortunately, we have no automatic "backport" mechanism in place which would copy over changes in the repository to the archived version in http://github.com/qooxdoo/documentation 's `gh-pages` branch. Thank you very much!