Treevirtual FontIcon support
qooxdoo/qooxdoo pull request #10198
Opened 2021-05-25 18:11 UTC by adrelino

This adds fonticon support to the table-based treevirtual, to allow proper styling in the new Tangible theme. 
See also [DemoBrowser](https://qooxdoo.org/qxl.demobrowser/#treevirtual~TreeVirtual.html), then select Tangible Dark theme.

Before: 
![TreeVirtual_Old](https://user-images.githubusercontent.com/6432001/119547296-3a404780-bd95-11eb-8a7d-849806f1793b.png)

After:
![TreeVirtual_new](https://user-images.githubusercontent.com/6432001/119547279-344a6680-bd95-11eb-9649-0bfcbd7f42ae.png)

2021-05-25 18:27 UTC, adrelino commented
After my last commit, the qx.ui.treevirtual.TreeVirtual() looks like this:
![TreeVirtual_ContractExpand](https://user-images.githubusercontent.com/6432001/119549231-4c22ea00-bd97-11eb-9438-160a53273f8c.png)

This is the same look as qx.ui.tree.Tree() and qx.ui.tree.VirtualTree() have in the Tangible theme.

2021-05-26 09:21 UTC, oetiker approved these changes
cool ...
the other themes, I take it are not affected ?

2021-05-26 09:22 UTC, oetiker commented
> After my last commit, the qx.ui.treevirtual.TreeVirtual() looks like this:
> ![TreeVirtual_ContractExpand](https://user-images.githubusercontent.com/6432001/119549231-4c22ea00-bd97-11eb-9438-160a53273f8c.png)
> 
> This is the same look as qx.ui.tree.Tree() and qx.ui.tree.VirtualTree() have in the Tangible theme.

only the vertical and horyzontal tree lines seem a bit out of place now ... I guess this should be hidden in tangible ...

2021-05-26 11:30 UTC, derrell requested changes
Looks nice. Thanks for the contribution.

2021-05-26 11:30 UTC, derrell commented on source/class/qx/ui/treevirtual/SimpleTreeDataCellRenderer.js
>        // Don't use an image tag.  They render differently in Firefox and IE7
Original code now needs to be indented

2021-05-26 13:00 UTC, adrelino commented
> only the vertical and horyzontal tree lines seem a bit out of place now ... I guess this should be hidden in tangible ...

ok, done in https://github.com/qooxdoo/qooxdoo/pull/10198/commits/9a4f7c6b2939e46b7d87c89c1f831baf2fa75faf

![TreeVirtual_final](https://user-images.githubusercontent.com/6432001/119663871-12072600-be33-11eb-9f70-0f395d8c591c.png)

2021-05-26 13:14 UTC, oetiker approved these changes
I like it

2021-05-26 13:16 UTC, derrell approved these changes

2021-05-26 13:56 UTC, cboulanger approved these changes

2021-05-28 06:19 UTC, level420 approved these changes

2021-06-02 11:54 UTC, adrelino commented
Why are the firefox tests all running for 6 hours and then timed/out cancelled?

2021-06-04 12:48 UTC, hkollmann approved these changes

2021-06-04 12:49 UTC, merged