minor fixes to `qx.dgata.Array`
qooxdoo/qooxdoo pull request #10205
Opened 2021-06-04 12:26 UTC by johnspackman

2021-06-04 12:55 UTC, hkollmann requested changes

2021-06-04 12:55 UTC, hkollmann commented on source/class/qx/data/Array.js
> +          var type = "add";
this should be let do avoid global var hints!

2021-06-04 13:42 UTC, derrell approved these changes

2021-06-04 15:54 UTC, oetiker approved these changes

2021-06-04 15:55 UTC, level420 approved these changes

2021-06-05 08:44 UTC, cboulanger approved these changes

2021-06-07 08:12 UTC, hkollmann approved these changes

2021-06-07 08:13 UTC, merged