adds utility to help choose contrasting colours
qooxdoo/qooxdoo pull request #10208
Opened 2021-06-04 12:27 UTC by johnspackman

2021-06-04 12:56 UTC, hkollmann approved these changes

2021-06-04 13:36 UTC, derrell requested changes

2021-06-04 13:36 UTC, derrell commented on source/class/qx/util/ColorUtil.js
> +      var yiq = ((r * 299) + (g * 587) + (b * 114)) / 1000;
Could you add a comment here please? What is `yiq` and what is this formula?

2021-06-04 13:47 UTC, derrell approved these changes

2021-06-05 08:49 UTC, cboulanger approved these changes

2021-06-06 15:18 UTC, oetiker approved these changes

2021-06-07 12:18 UTC, level420 approved these changes

2021-06-07 13:31 UTC, merged