Additons to `qx.ui.list` and `qx.ui.virtual`
qooxdoo/qooxdoo pull request #10202
Opened 2021-06-04 12:26 UTC by johnspackman

There are a lot of changes in this PR, to the list and to the underlying mechanism; this solves some bugs, but adds new features:

* Auto sizing rows and columns (varying sized rows allowed)
* Wrap rows onto multiple columns
* Support multiple columns (like a table), where each column has a specific type (eg a DateColumn etc)
* Fixes bugs with label rendering

There are BC issues here, although it should be noted that some of the bug fixes meant that BC was unavoidable, and also that there was code (eg some layers) which could not work.  There is more work to be done, but this is a good start.

2021-06-04 13:04 UTC, hkollmann requested changes
Could you add a comment for the BC issues in CHANGELOG.md?
Thanks.

2021-06-04 16:14 UTC, derrell requested changes

2021-06-04 16:14 UTC, derrell commented on source/class/qx/ui/list/List.js
> +	extend: qx.ui.virtual.core.Scroller,
Without reference to coding style, per se, can we avoid use of tabs for indentation? Qooxdoo has traditionally used 2 spaces of indentation. Tabs are "defined" as moving to multiples of 8 spaces, and in fact, that's how it appears, for example, in this github PR. That much indentation makes JavaScript lines really, really long. Do you think you can replace tabs with 2 spaces each in here?

2021-06-04 16:24 UTC, johnspackman commented
Yes, sorry it’s supposed to be 2 spaces, must be because I switched ide recently

Sent from my iPhone

> On 4 Jun 2021, at 17:12, Derrell Lipman ***@***.***> wrote:
> 
> ﻿
> @derrell requested changes on this pull request.
> 
> In source/class/qx/ui/list/List.js:
> 
> > -      }
> -    },
> -
> -
> -    /**
> -     * Event handler for the updated event of the 
> -     * qx.ui.virtual.layer.WidgetCell layer.
> -     *
> -     * Recalculates the item sizes in a deffered call,
> -     * which only happens if we have variable item heights
> -     */
> -    _onLayerUpdated: function () {
> -      if (this.isVariableItemHeight() === false) {
> -        return;
> +qx.Class.define("qx.ui.list.List", {
> +	extend: qx.ui.virtual.core.Scroller,
> Without reference to coding style, per se, can we avoid use of tabs for indentation? Qooxdoo has traditionally used 2 spaces of indentation. Tabs are "defined" as moving to multiples of 8 spaces, and in fact, that's how it appears, for example, in this github PR. That much indentation makes JavaScript lines really, really long. Do you think you can replace tabs with 2 spaces each in here?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-06 13:29 UTC, cboulanger approved these changes
Looking forward to seeing this in action - similarly you'll probably have some examples for the widgetbrowser and demobrowser ready for when this is merged?

2021-06-06 15:21 UTC, oetiker approved these changes

2021-06-07 08:09 UTC, hkollmann approved these changes

2021-06-07 08:13 UTC, johnspackman commented
oops, i missed the ui tests for this and checkboxlist, i'll add them shortly

2021-06-10 11:02 UTC, derrell approved these changes

2021-06-14 14:36 UTC, oetiker commented
@level420 ping ?

2021-06-14 21:05 UTC, level420 approved these changes

2021-06-15 06:35 UTC, oetiker commented
There still seeem to be lots of failing tests with chrome ... guess they have a common cause ?

2022-02-08 20:26 UTC, hkollmann commented
Due to es6ify this can not be merged any longer.
Can we close it @johnspackman ?

2022-02-08 20:28 UTC, closed without merging