fixes a bug where a missing Manifest.json in compile.json directory b…
qooxdoo/qooxdoo pull request #10209
Opened 2021-06-04 12:27 UTC by johnspackman

…reaks the compile;

stops running migrations for every compile;
adds application groups to the compile (so that a set of applications can be chosen for compilation from the command line)
fixes a bug where the sourcemapping URL is broken in some IDEs (eg VS code)
fixes a bug in resolving the Qooxdoo path, it now favours the qooxdoo that the `qx` command is in

2021-06-04 13:01 UTC, hkollmann approved these changes

2021-06-04 13:37 UTC, derrell approved these changes
Blind approval.

2021-06-04 14:04 UTC, oetiker commented on source/resource/qx/tool/schema/compile-1-0-0.json
> +                "type": "string"
```suggestion
                "type": "string",
                "pattern": "^[-_a-zA-Z0-9]+$"
```

2021-06-04 14:04 UTC, oetiker commented on source/resource/qx/tool/schema/compile-1-0-0.json
> +                  "type": "string"
```suggestion
                  "type": "string",
                  "pattern": "^[-_a-zA-Z0-9]+$"
```

2021-06-04 14:05 UTC, oetiker approved these changes

2021-06-06 13:21 UTC, cboulanger requested changes
Very godd addition. Could you add a short info to the documentation to this PR? Thank you.

2021-06-11 08:45 UTC, level420 approved these changes

2021-06-14 14:37 UTC, oetiker commented
@cboulanger anything missing still ?

2021-06-14 15:31 UTC, cboulanger approved these changes

2021-06-14 15:32 UTC, merged

2021-06-14 15:32 UTC, cboulanger commented
Thank you @johnspackman !