Adds CheckedList, CheckedSelectbox and data controller
qooxdoo/qooxdoo pull request #10201
Opened 2021-06-04 12:23 UTC by johnspackman

CheckedList (and CheckedSelectBox) are easier to use than multiple selection, because checkboxes cannot be accidentally turned off so easily and have a more appropriate appearance.  This PR also includes a controller for binding

2021-06-04 12:52 UTC, derrell requested changes
Looks useful!

2021-06-04 12:52 UTC, derrell commented on source/class/qx/data/controller/CheckedList.js
> + * The principal is thart the underlying `List` controller implementation has a model which
typo: `thart` vs `that`

2021-06-04 12:52 UTC, derrell commented on source/class/qx/data/controller/CheckedList.js
> +   * @param path {String} the path in the model for the caption
`path` is optional. Both `widget` and `path` default to null. I think these should be `qx.ui.core.Widget?null` and `String?null` respectively, as in the superclass:

```
   * @param target {qx.ui.core.Widget?null} The widget which should show the
   *   ListItems.
   *
   * @param labelPath {String?null} If the model contains objects, the labelPath
   *   is the path reference to the property in these objects which should be
   *   shown as label.
```

2021-06-04 12:52 UTC, derrell commented on source/class/qx/data/controller/CheckedList.js
> +          children[hash] = item;
It appears possible for multiple items to hash to "null" thus overwriting items in the children map. Is this confirmed to be acceptable here?

2021-06-06 13:25 UTC, cboulanger approved these changes
Another great addition. I assume you'll add examples to the Demo Browser and Widget Browser (also important so that Theme authors can check that their theme works with the new widgets).

2021-06-06 15:24 UTC, oetiker approved these changes

2021-06-07 08:08 UTC, hkollmann approved these changes

2021-06-07 12:16 UTC, level420 approved these changes

2021-06-10 11:00 UTC, derrell approved these changes

2021-06-10 13:23 UTC, merged