makes the format string available from `qx.util.format.DateFormat`
qooxdoo/qooxdoo pull request #10243
Opened 2021-07-28 09:49 UTC by johnspackman

2021-07-28 10:51 UTC, cboulanger approved these changes

2021-07-28 11:25 UTC, derrell requested changes

2021-07-28 11:25 UTC, derrell commented on source/class/qx/util/format/DateFormat.js
> +     * @returns {String}
The annotation here should be `@return` (singular)

2021-07-28 15:45 UTC, oetiker approved these changes

2021-07-28 20:13 UTC, hkollmann approved these changes

2021-07-29 10:11 UTC, level420 approved these changes

2021-07-29 11:02 UTC, derrell approved these changes

2021-08-02 18:22 UTC, merged