bug in detecting whether a webfont has been loaded
qooxdoo/qooxdoo pull request #10250
Opened 2021-08-11 11:06 UTC by johnspackman

fixes a minor issue where a listener is attached to detect the webfont being loaded, but if the webfont is already loaded the event will never fire in practice

2021-08-11 12:57 UTC, oetiker approved these changes

2021-08-11 15:22 UTC, level420 approved these changes

2021-08-11 15:53 UTC, lucapivato commented
And the same listener is added in AbstractFIeld.js, it should probably check isValid() there too.

2021-08-11 17:01 UTC, derrell requested changes

2021-08-11 17:01 UTC, derrell commented on source/class/qx/bom/webfonts/WebFont.js
> +      this.setValid(!!result.valid);
Are you sure this accomplishes the goal? The `changeValid` event will not be fired if the property is set to the same value it already has. Is there any possibility of that occurring here?

2021-10-11 13:06 UTC, derrell approved these changes

2021-10-14 10:59 UTC, hkollmann approved these changes

2021-10-15 07:45 UTC, cboulanger approved these changes

2021-10-15 08:17 UTC, merged