simplified publishing
qooxdoo/qooxdoo pull request #10286
Opened 2021-11-20 20:52 UTC by hkollmann

- shorten tests 
- remove dependency from qx.tool.compiler.Version.VERSION
- add afterProcessFinished to compiler api
- use afterProcessFinished for qx pkg publish to publish @qooxdoo/framework on npm

2021-11-20 21:00 UTC, cboulanger approved these changes

2021-11-21 16:47 UTC, derrell requested changes

2021-11-21 16:47 UTC, derrell commented on docs/development/compiler/configuration/api.md
> +- `load()`: Called to update the compilerConfig and
`and` what?

2021-11-21 17:17 UTC, hkollmann commented on docs/development/compiler/configuration/api.md
> +- `load()`: Called to update the compilerConfig and
removed

2021-11-21 21:57 UTC, oetiker approved these changes

2021-11-21 23:25 UTC, derrell approved these changes

2021-11-22 08:19 UTC, level420 approved these changes

2021-11-22 09:31 UTC, johnspackman approved these changes

2021-11-22 09:38 UTC, merged