ES5 Adds ARIA role to window and aria helper functions to widget
qooxdoo/qooxdoo pull request #10291
Opened 2021-12-07 14:59 UTC by ArturWesner

ES5 Version of [#10290](https://github.com/qooxdoo/qooxdoo/pull/10290)

2021-12-07 15:07 UTC, derrell requested changes

2021-12-07 15:07 UTC, derrell commented on source/class/qx/ui/core/Widget.js
> +      res = res ? `${res} ${idStr}` : idStr;
Template literals are not available in ES5.

2021-12-07 15:19 UTC, derrell approved these changes

2021-12-07 18:04 UTC, hkollmann approved these changes

2021-12-07 20:16 UTC, oetiker commented
@ArturWesner how about makeing this a PR to https://github.com/qooxdoo/qooxdoo/tree/latest directly ?

2021-12-08 06:42 UTC, cboulanger approved these changes

2021-12-08 09:04 UTC, ArturWesner commented
@oetiker Yes, thats what i thought/meant too.
Oops, seems like changing the branch from master to latest broke the PR. I thought it would kinda copy the commits onto the latest branch. Hmm. What should i do now? Create a new PR and delete this one?
Sorry for the inconvenience!

2021-12-08 10:23 UTC, oetiker commented
> @oetiker Yes, thats what i thought/meant too. Oops, seems like changing the branch from master to latest broke the PR. I thought it would kinda copy the commits onto the last commit of the latest branch. Hmm. What should i do now? Create a new PR and delete this one? Sorry for the inconvenience!

best is todo a rebase of your branch to latest and then push it `git fetch upstream; git rebase latest; git push --force`

2021-12-08 21:12 UTC, hkollmann commented
What's about the earlier pr https://github.com/qooxdoo/qooxdoo/commit/68b240c5404eee3b28a4651030c4886e5509e6e5?

Could you make a PR for latest too?

2021-12-09 07:18 UTC, oetiker approved these changes

2021-12-09 07:19 UTC, oetiker commented
> What's about the earlier pr [68b240c](https://github.com/qooxdoo/qooxdoo/commit/68b240c5404eee3b28a4651030c4886e5509e6e5)?
> 
> Could you make a PR for latest too?

this PR is for latest!

2021-12-09 07:32 UTC, ArturWesner commented
In the mentioned PR `const` and `let`needs to be replaced by `var`. And of course the changes should be applied to ./framework/source instead of ./source. 
I can create an extra PR if needed. Is there an better way to apply the directory change than creating a patch with `git format-patch` and applying it with `git apply --directory='framework'` ?

2021-12-09 09:05 UTC, hkollmann commented
just try it...

2021-12-09 12:15 UTC, cboulanger approved these changes

2021-12-09 13:11 UTC, level420 approved these changes

2021-12-13 17:30 UTC, merged