Fix babel
qooxdoo/qooxdoo pull request #10295
Opened 2021-12-10 07:59 UTC by hkollmann

- fix babel docs
- add doc fo new api bubble afterProcessFinished
- babel options are not handled as documented

2021-12-10 08:14 UTC, cboulanger approved these changes

2021-12-10 09:14 UTC, johnspackman approved these changes

2021-12-10 10:47 UTC, oetiker approved these changes

2021-12-13 13:54 UTC, level420 approved these changes

2021-12-14 17:28 UTC, derrell requested changes

2021-12-14 17:28 UTC, derrell commented on source/class/qx/tool/cli/commands/Compile.js
> +          data.babel = { options: data.babelOptions };
This isn't just adding `options`; it's overwriting `data.babel`. If before line 575, `data` contained:
```
data : 
{
  babel : 
  {
    x : "hello"
  },
  babelOptions : 
  {
    z : "hi"
  }
}
```

then after line 577, data now contains:
```
data : 
{
  babel : 
  {
    options : 
    {
      z : "hi"
    }
  }
}
```

`x` has been lost.

Unless the intent was to lose the original value of `data.babel`, I think line 577 should instead be:
```
data.babel.options = data.babelOptions;
```

2021-12-14 17:31 UTC, derrell commented on source/class/qx/tool/cli/commands/Compile.js
> +          data.babel = { options: data.babelOptions };
(followed possibly by `delete data.babelOptions;`)

2021-12-14 18:27 UTC, derrell approved these changes

2021-12-14 19:07 UTC, merged