https://github.com/qooxdoo/qooxdoo/issues/10133: move mangle-privates to compile.json
qooxdoo/qooxdoo pull request #10339
Opened 2022-01-19 15:31 UTC by hkollmann

2022-01-19 15:42 UTC, derrell requested changes

2022-01-19 15:42 UTC, derrell commented on source/resource/qx/tool/schema/compile-1-0-0.json
> +            "description": " Whether and how to mangle private identifiers. Can be overridden on a per application basis. Can be overridden on a per application basis.",
Repeated sentence "Can be overridden on a per application basis"

Also, it should be "per-application" (with a dash) here and other places where that phrase is used

2022-01-19 17:25 UTC, cboulanger approved these changes

2022-01-19 18:30 UTC, johnspackman approved these changes
Approving this change (thank you @hkollmann ) , my only thought is that perhaps in future command line options which change the output should be removed altogether and only allowed in compile.js?

Years ago I think the idea was that you could compile just with command line and no compile.js at all, but that's obviously not viable (not any more anyway), and I question the benefit of leaving them in.

2022-01-19 21:10 UTC, hkollmann commented
@johnspackman : You can compile without compile.js! Most of my projects do so.

2022-01-19 22:23 UTC, johnspackman commented
> @johnspackman : You can compile without compile.js! Most of my projects do so.

Oh wow!  OK I take it all back! :) 👍

2022-01-20 09:51 UTC, oetiker commented
according to semantic versioning, the version of the schema should change when it ismodified .. since this change is compatible, the version number would be 1-1-0 ...

2022-01-21 12:03 UTC, hkollmann commented
@oetiker : this changes are introduced here https://github.com/qooxdoo/qooxdoo/commit/1b6c45e5b2a4658030e52608c1b26e9f6c50670d#diff-2c50702c8b657fb45f0b13b2b56b8f8ec10ad4a87a76ed43d2b7292ef4152795. But where lost.

We discussed the version change sometime ago the result that it will bring us into an update hell...

2022-01-21 12:27 UTC, oetiker commented
> @oetiker : this changes are introduced here [1b6c45e#diff-2c50702c8b657fb45f0b13b2b56b8f8ec10ad4a87a76ed43d2b7292ef4152795](https://github.com/qooxdoo/qooxdoo/commit/1b6c45e5b2a4658030e52608c1b26e9f6c50670d#diff-2c50702c8b657fb45f0b13b2b56b8f8ec10ad4a87a76ed43d2b7292ef4152795). But where lost.
> 
> We discussed the version change sometime ago the result that it will bring us into an update hell...

oh ... missed that one ... well can't help you there ... I can't do more than provide all the tools for sustainability if the mode is to ignore it ... well ..

2022-01-21 12:27 UTC, oetiker approved these changes

2022-01-21 13:58 UTC, johnspackman commented
>> We discussed the version change sometime ago the result that it will bring us into an update hell...

>if the mode is to ignore it ... well ..

It's a temporary issue - the compiler requires the current version of compile.json and Manifest.json, so if we change the version number updates then everything needs to be changed (eg Manifest.json means that every plugin will need to have the schema version changed).  For users who switch between compiler versions, this means that the plugin versions have to be switched back and forth also, for no good reason. 

One day there would be a simple mapping between version numbers, eg a v1.0.0 can be translated into v2.0.0 on the fly so that the compiler can work

2022-01-25 21:08 UTC, derrell approved these changes

2022-01-25 22:03 UTC, level420 approved these changes

2022-01-25 22:07 UTC, cboulanger approved these changes

2022-01-26 12:43 UTC, merged