Adds the ability for multiple events with promises to be tracked and …
qooxdoo/qooxdoo pull request #10439
Opened 2022-08-17 12:30 UTC by johnspackman

…awaited on

2022-08-17 13:04 UTC, derrell requested changes
Can you explain a bit of what this is doing? It's in a mixin that will likely cause it to have wide-ranging consequences so I'd like to fully understand it.

2022-08-17 13:10 UTC, johnspackman commented
events can be asynchronous, and can themselves trigger actions which are asynchronous - when they do so, they return a Promise.  If you're just firing one event (and there are no side effects) then it is easy to await firing, but lots of code does not do that.  This fix tracks any promises returned from an event being fired, and allows the caller to await for them to all be resolved.

2022-08-17 13:38 UTC, derrell approved these changes

2022-08-17 15:07 UTC, cboulanger commented on source/class/qx/core/MEvent.js
> +     * Internal helper method to track promises returned from evcent handlers
s/evcent/event/

2022-08-17 15:08 UTC, cboulanger approved these changes

2022-08-17 15:20 UTC, hkollmann approved these changes

2022-08-18 09:09 UTC, oetiker approved these changes

2022-08-20 16:20 UTC, level420 approved these changes

2022-08-24 05:44 UTC, merged

2022-08-24 05:45 UTC, hkollmann commented
Thanks @johnspackman !