adding support for proxy classes
qooxdoo/qooxdoo pull request #10446
Opened 2022-08-17 13:13 UTC by johnspackman

2022-08-17 13:23 UTC, derrell requested changes
The changes look fine, but the PR title says "proxy classes" but there's nothing in this PR about proxy classes. What is a proxy class, and what have these changes to do with it?

2022-08-17 14:23 UTC, johnspackman commented
I've just realised that the docs for this were included some time ago, but the functionality wasn't!  It's documented here: https://github.com/qooxdoo/qooxdoo/blob/master/docs/development/compiler/configuration/compile.md

Basically, `proxySourcePath` allows an alternative source path to be searched when compiling; this allows "proxy" classes to be generated, which have a special meaning on a given target.  For example, if you have a class that exists on the server, you might generate a "proxy" version of that for use on the client, and that "proxy" version would use async I/O to connect to the server.

2022-08-17 15:02 UTC, cboulanger approved these changes

2022-08-17 16:12 UTC, oetiker approved these changes

2022-08-18 12:51 UTC, derrell approved these changes

2022-08-20 18:53 UTC, level420 approved these changes

2022-08-23 16:28 UTC, hkollmann approved these changes

2022-08-23 16:28 UTC, merged

2022-08-23 16:28 UTC, hkollmann commented
Thanks @johnspackman !