improve error messages
qooxdoo/qooxdoo pull request #10441
Opened 2022-08-17 12:34 UTC by johnspackman

2022-08-17 13:11 UTC, derrell requested changes

2022-08-17 13:11 UTC, derrell commented on source/class/qx/core/MProperty.js
> +     * @param data {Map | String} a map of property values. The key is the name of the property.
Now that there is an actual type called `Map`, I think we're poorly served by using the old meaning of `Map` (for `Object`). I agree that `Object` is insufficiently specific, and that it's an Object being used as a Map, but we should either find another name to indicate an Object used as a Map (`Dictionary`?) or continue to use `Object` for these cases.

2022-08-17 13:29 UTC, derrell approved these changes

2022-08-17 15:04 UTC, cboulanger approved these changes

2022-08-18 09:08 UTC, oetiker approved these changes

2022-08-18 09:51 UTC, hkollmann approved these changes

2022-08-21 07:11 UTC, level420 approved these changes

2022-08-23 16:24 UTC, merged

2022-08-23 16:24 UTC, hkollmann commented
Thanks @johnspackman !