fix schema validation to work on compile.js or compile.json
qooxdoo/qooxdoo pull request #10450
Opened 2022-08-23 15:50 UTC by johnspackman

2022-08-23 16:02 UTC, cboulanger approved these changes

2022-08-23 16:10 UTC, oetiker approved these changes

2022-08-23 16:26 UTC, hkollmann approved these changes

2022-08-23 18:40 UTC, derrell requested changes

2022-08-23 18:40 UTC, derrell commented on source/class/qx/tool/cli/Cli.js
> +      // Validate compile.json against the schema
The title of this PR says it now also validates compile.js. Should this comment mention that too?

2022-08-24 12:34 UTC, derrell approved these changes

2022-08-25 07:07 UTC, level420 approved these changes

2022-08-27 15:33 UTC, merged

2022-08-27 15:33 UTC, hkollmann commented
Thanks @johnspackman !