fixes a bug where the context is missing from Slider event handlers
qooxdoo/qooxdoo pull request #10451
Opened 2022-08-24 05:04 UTC by johnspackman

2022-08-24 05:08 UTC, cboulanger approved these changes

2022-08-24 05:49 UTC, hkollmann approved these changes

2022-08-24 06:33 UTC, oetiker approved these changes

2022-08-24 12:43 UTC, derrell requested changes
There is a call to `removeListener` that also needs to be updated with the context, or I believe the listener won't be removed.

2022-08-24 12:48 UTC, johnspackman commented
done

2022-08-24 13:23 UTC, derrell approved these changes

2022-08-25 07:07 UTC, level420 approved these changes

2022-08-27 19:50 UTC, merged

2022-08-27 19:50 UTC, hkollmann commented
Thanks. @johnspackman !