release info for 7.4
qooxdoo/qooxdoo pull request #10490
Opened 2022-11-21 19:47 UTC by hkollmann

2022-11-21 19:51 UTC, derrell requested changes

2022-11-21 19:51 UTC, derrell commented on docs/release-notes.7.0.md
> +- compile.json: localModules can now be used in the root of the file. So you can adress the modules for all apllications.
s/adress/address/
s/apllications/applications/

2022-11-21 19:51 UTC, derrell commented on docs/release-notes.7.0.md
> +- browserify of npm modules: Browserify of the used npm modules is a time cosuming process. No it's checked if it's really neccesary.
s/Browserify of the/Broserifying the/
s/time cosuming/time-consuming/
s/No it's chechecked if/Now it's checked whether/

2022-11-21 19:51 UTC, derrell commented on docs/release-notes.7.0.md
> +    - commonjs-browserify.js do not exits
s/do not exits/does not exist/

2022-11-21 19:51 UTC, derrell commented on docs/release-notes.7.0.md
> +    - One of the localModules are newer compared to the last run
s/One of/One or more of/

2022-11-21 20:56 UTC, derrell requested changes

2022-11-21 20:56 UTC, derrell commented on docs/release-notes.7.0.md
> +- browserifying the npm modules: Browserify of the used npm modules is a time-consuming process. No it's checked whether it's really neccesary.
s/No it's checked/Now it's checked/

2022-11-21 21:00 UTC, derrell approved these changes

2022-11-22 08:45 UTC, cboulanger approved these changes

2022-11-22 10:05 UTC, oetiker approved these changes

2022-11-22 18:19 UTC, level420 approved these changes

2022-11-23 23:25 UTC, johnspackman approved these changes

2022-11-24 11:06 UTC, merged