Grammar and reference fixes
qooxdoo/qooxdoo pull request #10525
Opened 2023-01-20 21:49 UTC by goldim

Done other parts of docs except desktop which was done in prev PR

2023-01-20 22:10 UTC, cboulanger approved these changes
Again, thanks for doing this!

2023-01-21 17:19 UTC, derrell requested changes

2023-01-21 17:19 UTC, derrell commented on docs/development/howto/icon_fonts.md
> +fonts. It is not possible to use these icon fonts based images in decorators.
s/icon fonts based/icon fonts-based/

2023-01-21 17:19 UTC, derrell commented on docs/development/howto/internationalization.md
> +returned which can be a bit confusing if done accidentally, but is correct
s/returned which/returned, which/
(add comma)

2023-01-21 17:19 UTC, derrell commented on docs/mobile/mobile_overview.md
> +- Widgets: Widget / Feature missing? Create a widget a post it back to us.
s/Create a widget a post/Create a widget and submit it as a Pull Request/

(I think that's what's intended here...???)

2023-01-21 17:19 UTC, derrell commented on docs/release-notes.6.0.md
> +Accessibility is an important topic in nowadays web development
s/nowadays/modern/

2023-01-21 17:19 UTC, derrell commented on docs/tutorial/twitter/tutorial-part-2.md
> +element, so it won't be visible. Fixing it means adding an element, in our case
s/It contains not a single elelment/It doesn't contain any elements/

2023-01-21 17:19 UTC, derrell commented on docs/tutorial/twitter/tutorial-part-2.md
> +so this in this.fireEvent() is resolved correctly.
s/this/`this`/

2023-01-21 17:19 UTC, derrell commented on docs/tutorial/twitter/tutorial-part-2.md
> +good. Why don't we just give it a fixed width to fit its height?
This is a rhetorical question, not really a question. I'd either leave it as a period, or replace the period with a colon (`:`)

2023-01-21 18:17 UTC, goldim commented
Big thanks @derrell gonna fix it soon

2023-01-21 18:35 UTC, goldim commented on docs/core/data_binding/controller.md
> +Also, forms do have a special controller. The form controller uses a
Heard that do or does could emphasize a verb in affirmative  sentences. Maybe is it this case?

2023-01-21 21:08 UTC, derrell commented on docs/core/data_binding/controller.md
> +Also, forms do have a special controller. The form controller uses a
It's an extreme emphasis, e.g., "You DO want to go" is much stronger than just, "You want to go." In this case the extreme emphasis isn't appropriate.

2023-01-21 21:10 UTC, goldim commented on docs/core/data_binding/controller.md
> +Also, forms do have a special controller. The form controller uses a
Got it, thanks for clarifying

2023-01-22 15:47 UTC, hkollmann approved these changes

2023-01-23 08:31 UTC, oetiker approved these changes

2023-01-23 10:03 UTC, johnspackman approved these changes

2023-01-23 14:05 UTC, derrell approved these changes

2023-01-23 16:25 UTC, merged