Remove obsolete parts and edit desktop
qooxdoo/qooxdoo pull request #10530
Opened 2023-01-26 09:19 UTC by goldim

- removed obsolete parts (e.g. for qooxdoo 5)
- removed spaces from sidebar page
- article tech_website_apies moved to desktop
- added two links in sidebar (inline and tech_website_apies)
- edited desktop (es6, codes marked accordingly json5 or javascript, noticed and fixed some bad links and so on)

2023-01-26 09:28 UTC, cboulanger approved these changes
Again: thank you for this clean-up, very important work!

2023-01-26 10:36 UTC, johnspackman approved these changes

2023-01-26 14:40 UTC, derrell requested changes
Sorry, this requested change wasn't one from your PR but rather, adjacent to it that I noticed while reviewing.

2023-01-26 14:40 UTC, derrell commented on docs/desktop/gui/table_styling.md
>  // these two lines have to inserted in your application color theme
these two lines have to BE inserted

2023-01-26 15:03 UTC, goldim commented on docs/desktop/gui/table_styling.md
>  // these two lines have to inserted in your application color theme
no problem, will fix it

2023-01-26 19:32 UTC, derrell approved these changes

2023-01-26 20:16 UTC, hkollmann approved these changes

2023-01-27 18:27 UTC, level420 approved these changes

2023-01-30 08:01 UTC, oetiker approved these changes

2023-01-30 09:33 UTC, merged