add release info for 7.6
qooxdoo/qooxdoo pull request #10562
Opened 2023-03-19 17:39 UTC by hkollmann

2023-03-19 18:08 UTC, cboulanger approved these changes

2023-03-19 20:43 UTC, oetiker commented on docs/release-notes.7.0.md
> +The benefits of all this is faster compiles, with smaller build targets - and no space consumed by icon fonts at all
```suggestion
The benefits of all this is faster compiles, with smaller build targets - and no space consumed by the materialicon fonts if they are not used (as this this was the case in the earlier 7.x releases).
```

2023-03-19 20:44 UTC, oetiker approved these changes

2023-03-19 22:02 UTC, derrell requested changes

2023-03-19 22:02 UTC, derrell commented on docs/release-notes.7.0.md
> +The benefits of all this is faster compiles, with smaller build targets - and no space consumed by the materialicon fonts if they are not used (as this this was the case in the earlier 7.x releases).
```suggestion
The benefits of all this is faster compiles, with smaller build targets - and no space consumed by the `materialicon` fonts if they are not used (as this was the case in the earlier 7.x releases).
```

2023-03-20 08:03 UTC, goldim approved these changes

2023-03-20 12:39 UTC, derrell approved these changes

2023-03-20 14:10 UTC, goldim requested changes
#10564

2023-04-07 15:25 UTC, goldim approved these changes

2023-04-12 18:46 UTC, johnspackman approved these changes

2023-04-13 17:42 UTC, merged