FileSelectorButton doesn't fire event if disabled
qooxdoo/qooxdoo pull request #10578
Opened 2023-04-06 08:33 UTC by goldim

Fixed #10548

2023-04-06 08:41 UTC, goldim commented
Not sure if do the same for "tap" event. The "execute" event is not fired I can't catch it.

2023-04-06 09:19 UTC, hkollmann approved these changes

2023-04-06 09:20 UTC, hkollmann commented
@goldim : BTW you can use es6 syntax here!

2023-04-06 09:26 UTC, goldim commented
@hkollmann Exactly! Thanks.

2023-04-06 14:10 UTC, oetiker approved these changes

2023-04-06 14:17 UTC, derrell requested changes

2023-04-06 14:25 UTC, goldim commented on source/class/qx/ui/form/FileSelectorButton.js
> +      input.addListener("click", e => {
@derrell any suggestion?

2023-04-06 14:48 UTC, derrell requested changes

2023-04-06 14:48 UTC, derrell commented on source/class/qx/ui/form/FileSelectorButton.js
> +      input.addListener("click", e => {
I guess my question is why it's even getting to here, on "click"? It's a `qx.html.Input`, and looking in that source code, it has this:

```
    setEnabled(value) {
      this.__enabled = value;

      this.setAttribute("disabled", value === false);
      ...
```

So why is a disabled input able to generate events? Maybe the value passed to `setEnabled` isn't a strict boolean, `false`? Maybe the above line should be:

```
      this.setAttribute("disabled", ! value);
```

2023-04-07 12:37 UTC, derrell approved these changes
This looks like it fixes the bug in `FileSelectorButton`. I fear it still leaves a bug in anything else that uses `Input` since I don't understand how a disabled element can fire an event...

2023-04-07 13:08 UTC, goldim commented
@derrell there is no 100% chance to avoid an error. There is a button which includes an input and I don't see how they are linked talking about enabled property. If the button is a container for input then I think changing a button property will lead to changing the similar input property. And what errors could happen looking at what I changed. Ive just bound enabled prop of two widgets.

2023-04-07 13:14 UTC, derrell commented
@goldim In qx.html.Input, this line:

```
this.setAttribute("disabled", value === false);
```

is setting the `disabled` attribute of the DOM element. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

Since a disabled DOM element can't be focused, etc., I would expect that it couldn't generate an event. Thus, my assumption is that line of code isn't doing what we expect, possibly because the argument to `setEnabled` is something falsy like `0`, but not `false` itself, so the element isn't being disabled.

2023-04-07 13:17 UTC, derrell commented
I commented, but deleted my comment. You are correct. Your change looks good.

2023-04-12 18:47 UTC, johnspackman approved these changes

2023-04-13 08:17 UTC, cboulanger approved these changes

2023-04-13 08:29 UTC, level420 approved these changes

2023-04-13 12:23 UTC, merged

2023-04-13 12:23 UTC, hkollmann commented
Thanks @goldim