Sometimes getWindow is absent what leads call of this method to an error
qooxdoo/qooxdoo pull request #10576
Opened 2023-04-04 12:27 UTC by goldim

The error is detected in API viewer and described in https://github.com/qooxdoo/qxl.apiviewer/issues/54 .

2023-04-04 12:56 UTC, oetiker approved these changes

2023-04-04 12:59 UTC, derrell requested changes
I wonder if this is covering up the problem rather than fixing it? When is `getWindow` ever defined? It's not used anyplace else in this file, and this isn't a mixin...??? Is a better solution to delete that entire line 475?

2023-04-04 13:03 UTC, goldim commented
@derrell as I get it is derived from JS Object. Sometimes it has this method sometimes doesn't I don't know why. Removing this line the same as my edit but I think more risky bc I don't know what is behind this change will happen.

2023-04-04 13:10 UTC, derrell approved these changes

2023-04-04 18:42 UTC, hkollmann approved these changes

2023-04-12 18:46 UTC, johnspackman approved these changes

2023-04-13 08:17 UTC, cboulanger approved these changes

2023-04-13 08:59 UTC, level420 approved these changes

2023-04-13 10:42 UTC, merged