Process no compile.json situation
qooxdoo/qooxdoo pull request #10579
Opened 2023-04-06 09:24 UTC by goldim

Fix #10577

2023-04-06 09:36 UTC, hkollmann approved these changes

2023-04-06 14:09 UTC, oetiker approved these changes

2023-04-06 14:11 UTC, derrell approved these changes

2023-04-06 17:36 UTC, hkollmann requested changes
seems that the tests do not run any longer.
please try 
```qx create myapp -I --type=server -v```
and check if compile.json is v´created.

2023-04-06 20:52 UTC, goldim commented
@hkollmann Doesn't work. Seems like `create` command uses `load` method to create empty config object.

2023-04-06 20:58 UTC, hkollmann commented
Then your changebdo not work 🥺

2023-04-12 18:50 UTC, johnspackman commented
@goldim does this work if there is a compile.js and no compile.json?

2023-04-12 19:26 UTC, goldim commented
@johnspackman no it doesn't. I'll try to fix it.

2023-04-13 08:59 UTC, hkollmann commented
@goldim : any progress with this?

2023-04-13 09:17 UTC, goldim commented
@hkollmann no, so fa. If it blocks the release, just ignore/skip this PR. Probably I may close it.

2023-04-13 10:40 UTC, cboulanger approved these changes
Looks good to me but I have no idea about possible side effects

2023-04-13 10:45 UTC, hkollmann approved these changes

2023-04-13 12:57 UTC, derrell requested changes

2023-04-13 13:04 UTC, goldim commented on source/class/qx/tool/cli/commands/Compile.js
> +        qx.tool.compiler.Console.error("Cannot find neither compile.json nor compile.js");
I would agree about can not but in code of framework there are a lot of "Cannot". I do not know if it was done on purpose or not.

2023-04-13 13:07 UTC, derrell commented on source/class/qx/tool/cli/commands/Compile.js
> +        qx.tool.compiler.Console.error("Cannot find neither compile.json nor compile.js");
No problem. "Cannot" is a less-used but acceptable contraction for "can not". If it's used frequently, that's fine. So only my change from `neither` to `either` should be retained.

2023-04-13 13:19 UTC, derrell approved these changes

2023-04-13 14:05 UTC, oetiker approved these changes

2023-04-13 15:09 UTC, hkollmann approved these changes

2023-04-13 15:12 UTC, johnspackman approved these changes

2023-04-13 15:22 UTC, merged