Fixed active and modal state initialization.
qooxdoo/qooxdoo pull request #10597
Opened 2023-05-27 20:10 UTC by lucapivato

See #10596

2023-05-28 00:49 UTC, goldim requested changes
`initProperty" leads to `removeState` but there is no state. Not sure if anything wrong happens in this case. I think checking old value on null value will exclude this case.

2023-05-28 01:13 UTC, lucapivato commented
Calling removeState on a state that is not set is quite common. States are just fields of the __states map.

2023-05-28 09:10 UTC, goldim approved these changes

2023-05-29 11:28 UTC, oetiker approved these changes

2023-05-29 13:53 UTC, derrell approved these changes

2023-05-29 14:04 UTC, cboulanger approved these changes

2023-05-29 20:38 UTC, hkollmann approved these changes

2023-05-30 11:53 UTC, level420 approved these changes

2023-05-30 17:47 UTC, merged

2023-05-30 17:47 UTC, hkollmann commented
Thanks @lucapivato !