More fixes for webfont loading
qooxdoo/qooxdoo pull request #10602
Opened 2023-06-05 07:16 UTC by johnspackman

fixes some bugs in font loading: order of libraries is preserved; font-face src is corrected; manifest fix;

2023-06-05 07:22 UTC, oetiker approved these changes

2023-06-05 07:32 UTC, hkollmann requested changes
Should´nt foliojs-fork/fontkit in line 71 removed then?

2023-06-05 08:19 UTC, goldim commented
@johnspackman thank you for replacing dependency. I also wanted to make a PR where the fork was replaced by original library. And seems like original one now more fresh then fork which supposed to be newer than original (in fork description said that original library hasn't been updated during long time). Btw tests are successful on my local machine.

2023-06-05 08:26 UTC, goldim commented on source/class/qx/tool/cli/commands/ExportGlyphs.js
> +      /*
Should it be left as commented?

2023-06-05 09:08 UTC, goldim commented
@johnspackman there is one more usage of the fork in file `qx.tool.compiler.app.WebFont`

2023-06-16 09:12 UTC, goldim approved these changes

2023-06-22 07:26 UTC, hkollmann approved these changes

2023-06-26 07:02 UTC, hkollmann commented
@johnspackman: Could you have a loók at the conflicts and can you replace the package-lock.json?

2023-06-26 07:36 UTC, goldim commented
Also some tests are still failed.

2023-06-29 07:56 UTC, hkollmann commented
@johnspackman : Any idea what happens with test-cli tests?

2023-07-11 05:38 UTC, cboulanger approved these changes

2023-07-11 05:39 UTC, cboulanger approved these changes
I don't use mobile so trusting you here

2023-07-13 12:53 UTC, derrell approved these changes

2023-07-13 14:38 UTC, merged