Added posibility to scroll area by dragging area
qooxdoo/qooxdoo pull request #10635
Opened 2023-10-27 12:24 UTC by goldim

2023-10-27 13:19 UTC, derrell requested changes

2023-10-27 13:19 UTC, derrell commented on source/class/qx/ui/core/scroll/MRoll.js
> +
`onlyRoll` doesn't seem, to me, to indicate what this feature is allowing and preventing. What do you think of this rename of the property (and updated comment), instead?

```
  /**
   * Allow scrolling by dragging the area. CAUTION: Enabling this property disallows the capability of drag&drop.
   */
  properties: {
    scrollByDrag: {
      init: false,
      check: "Boolean"
    }
  },
```

2023-10-27 13:28 UTC, derrell approved these changes

2023-10-28 06:19 UTC, hkollmann approved these changes

2023-10-28 11:02 UTC, cboulanger commented
Maybe add this to release notes?

2023-10-28 11:02 UTC, cboulanger approved these changes

2023-10-28 14:52 UTC, hkollmann approved these changes

2023-10-29 10:22 UTC, oetiker approved these changes

2023-10-30 11:10 UTC, level420 approved these changes

2023-10-30 11:23 UTC, goldim commented
> Maybe add this to release notes?

 Notes in qooxdoo docs for version 7.7 ?

2023-10-30 15:16 UTC, merged