Fix punycode warning
qooxdoo/qooxdoo pull request #10675
Opened 2024-03-26 16:51 UTC by johnspackman

The punycode warning is caused by old octokit and node-fetch; node-fetch is removed from this as our use is trivial, and octokit is upgraded

2024-03-26 18:15 UTC, cboulanger approved these changes

2024-03-26 19:41 UTC, hkollmann approved these changes

2024-03-27 10:04 UTC, goldim requested changes
Tests have to pass

2024-03-27 10:36 UTC, hkollmann commented
It's just a linter problem

2024-03-27 12:26 UTC, derrell approved these changes

2024-03-27 12:53 UTC, johnspackman commented
superceeded by https://github.com/qooxdoo/qooxdoo/pull/10678

2024-03-27 12:53 UTC, closed without merging