fixes a bug where `qx.html.Image` breaks JSX
qooxdoo/qooxdoo pull request #10680
Opened 2024-03-28 09:49 UTC by johnspackman

fixes a bug where `qx.html.Image` is only suitable for `qx.ui.basic.Image` and should not be part of the JSX / VDOM because it breaks the `<img>` tag

2024-03-28 10:44 UTC, goldim commented on source/class/qx/html/Element.js
> + * NOTE:: This classes used to require `qx.module.Animation` but this brings in a huge
```suggestion
 * NOTE:: These classes used to require `qx.module.Animation` but this brings in a huge
```

2024-03-28 10:45 UTC, goldim commented on source/class/qx/html/Element.js
> +     */ setStyles(map, direct) {
Broken formatting

2024-03-28 10:45 UTC, goldim commented on source/class/qx/html/Node.js
> + * NOTE:: This classes used to require `qx.module.Animation` but this brings in a huge
```suggestion
 * NOTE:: These classes used to require `qx.module.Animation` but this brings in a huge
```

2024-03-28 10:46 UTC, goldim requested changes
Broken formatting possible somehow to fix?

2024-03-28 12:54 UTC, derrell requested changes

2024-03-28 12:54 UTC, derrell commented on source/class/qx/application/AbstractGui.js
> +    }, // interface method
The `// interface method` applies to `terminate`, not to `close`. I think this whitespace was deleted accidentally.

2024-03-28 12:54 UTC, derrell commented on source/class/qx/html/Node.js
> +    */ /**
Broken formatting

2024-03-28 12:54 UTC, derrell commented on source/class/qx/html/Node.js
> +     */ registerProperty(key, get, set, serialize) {
Broken formatting

2024-03-28 12:54 UTC, derrell commented on source/class/qx/html/Node.js
> +     */ _setProperty(key, value, direct) {
Broken formatting

2024-03-28 13:12 UTC, johnspackman commented on source/class/qx/html/Element.js
> +     */ setStyles(map, direct) {
done

2024-03-28 13:17 UTC, johnspackman commented on source/class/qx/html/Node.js
> +     */ registerProperty(key, get, set, serialize) {
done

2024-03-28 13:17 UTC, johnspackman commented on source/class/qx/html/Node.js
> +     */ _setProperty(key, value, direct) {
done

2024-03-28 13:18 UTC, johnspackman commented
WRT to the formatting issue - prettier keeps breaking things.  I think i've caught them all and put them back, and included turning off the commit hook that was causing it to happen every commit 🙄

2024-03-28 13:48 UTC, goldim commented
@johnspackman should this hook be uncommented now after changes?

2024-03-28 14:23 UTC, johnspackman commented
> @johnspackman should this hook be uncommented now after changes?

just been trying to make a PR to fix this, but it turns out that it is down to babel mangling the tree before prettier gets involved - and unfortunately, prettier isn't able to fix it.

This means that es6ify should not be used routinely on commits - but prettier should.  I've fixed it, although it won't work on Windows unless there is a bash

2024-03-28 15:35 UTC, goldim approved these changes

2024-04-02 13:30 UTC, hkollmann requested changes

2024-04-02 14:13 UTC, johnspackman commented on .github/hooks/pre-commit
> +done
That would be useful, but I didn't have time and the current implementation breaks code formatting on every commit; I did a quick google, and as I understand it pre-commit hooks don't support windows except as bash scripts - I found an article saying that if you want to run a powershell cmd, you have to write a bash script and get it to run powershell.exe, eg:

```
#!/bin/sh
echo 
exec powershell.exe -ExecutionPolicy RemoteSigned -File '.\pre-commit.ps1'
exit
```

That may be an old article but the previous `pre-commit` had comment lines with `#`, and my Windows says that's not allowed.  Does the hook definitely run on your windows PC?

2024-04-02 14:29 UTC, hkollmann commented on .github/hooks/pre-commit
> +done
Yes the pre-commit with qx es6ify do work. # is'nt a valid comment sign in windows - that's the reason why you get the error.
What's about building a qx prettier command based on the es6ify command? es6ify just do the git calls with the parameter --git-pre-commit.
But this should be another PR.
So i suggest to remove the pre-commit commands completely in this PR and write an issue about creating a prettier command

2024-04-02 14:46 UTC, hkollmann approved these changes

2024-04-02 14:47 UTC, johnspackman commented on .github/hooks/pre-commit
> +done
done https://github.com/qooxdoo/qooxdoo/issues/10682

2024-04-04 12:11 UTC, oetiker approved these changes

2024-04-05 20:17 UTC, derrell requested changes

2024-04-05 20:17 UTC, derrell commented on source/class/qx/html/Node.js
> +    */ /**
This is showing as still-broken formatting.

2024-04-07 12:43 UTC, derrell approved these changes

2024-04-07 15:33 UTC, cboulanger approved these changes

2024-04-07 17:04 UTC, merged