adds a `privateArtifacts` option to `compile.json`
qooxdoo/qooxdoo pull request #10681
Opened 2024-03-28 09:50 UTC by johnspackman

This adds a `privateArtifacts` option to `compile.json` to allow all urls to be locked within an application directory

2024-03-28 12:24 UTC, cboulanger approved these changes

2024-03-28 12:59 UTC, derrell requested changes

2024-03-28 12:59 UTC, derrell commented on docs/development/compiler/configuration/compile.md
> +When the compiler generates an application(s), it creates `transpiled` and `resource`
grammar problem with plural. How about "generates one or more applications..."

2024-03-28 13:07 UTC, derrell approved these changes

2024-03-28 13:13 UTC, johnspackman commented on docs/development/compiler/configuration/compile.md
> +When the compiler generates an application(s), it creates `transpiled` and `resource`
done

2024-03-28 22:57 UTC, hkollmann approved these changes

2024-03-29 08:30 UTC, goldim commented
@johnspackman I can't compile your PR bc the compiler complains on new option. Is it relative with `known-good`?

2024-03-29 10:17 UTC, johnspackman commented
> Has this to be updated https://qooxdoo.org/schema/compile-1-0-0.json

Yes, I think that gets updated automatically when we do a release, but until then you'll get errors 

> after compiling with option nothing changed: all files on the same with app folder in target folder.

It is intentional that the files are still in the same place - but if you look at your generated `myappname/index.js` you'll see that the path to the files (resources and transpiled directories) has changed; the intention of this change is to allow you to have a URL on your web server where you only expose (or set permissions for) the application directory, and you would need to mount virtual folders within that URL.

EG in order to have an application at the root (eg `http://www.mywebsite.com/`, the `transpiled` and `resource` directory cannot be in `../transpiled`

Where there are multiple apps in a build, the `resource` and `transpiled` directories on disk need to be shared, hence the need to add virtual folders.

2024-03-29 12:06 UTC, goldim approved these changes

2024-04-02 11:49 UTC, oetiker approved these changes

2024-04-02 13:22 UTC, merged