Placeholder text does not get correct theme color.
qooxdoo/qooxdoo pull request #10695
Opened 2024-05-13 13:57 UTC by rijckrocket

Code in ui/form/AbstractField.js looks broken for some time to me (11th March 2013). __stylesheet was replaced on most places by using "global stylesheet" code.

But the _onChangeTheme() function still contains this if statement: if (!this.__useQxPlaceholder && qx.ui.form.AbstractField.__stylesheet) (which is not used any more) So the color from the loaded theme is never applied.

Now using the theme name to check when an update is needed.

Issue: #10694

2024-05-13 14:10 UTC, johnspackman requested changes

2024-05-13 14:14 UTC, rijckrocket commented on source/class/qx/ui/form/AbstractField.js
> +      if (qx.ui.form.AbstractField.__addedPlaceholderRules === ajaxclient.ThemeLoader.getInstance().getCurrentThemeName()) {
Ah, Sorry applied from wrong source. Will fix.

2024-05-13 14:44 UTC, rijckrocket commented on source/class/qx/ui/form/AbstractField.js
> +      if (qx.ui.form.AbstractField.__addedPlaceholderRules === ajaxclient.ThemeLoader.getInstance().getCurrentThemeName()) {
Applied corrected function call.

2024-05-13 18:28 UTC, goldim approved these changes
Now it works! Great, thank you.

2024-05-13 19:28 UTC, cboulanger approved these changes

2024-05-13 20:36 UTC, johnspackman approved these changes

2024-05-14 15:16 UTC, hkollmann approved these changes

2024-05-15 12:00 UTC, oetiker approved these changes

2024-05-17 09:23 UTC, merged