Added checking content on undefined value to fix testRedefineItem
qooxdoo/qooxdoo pull request #10731
Opened 2024-10-10 13:19 UTC by goldim

Fast fix for unit test `testRedefineItem` which I've spotted in my pull request https://github.com/qooxdoo/qooxdoo/pull/10730.
It is not only one test if I get rid of this test next failed test is also related with `qx.ui.form.Form`. It happens not because of my changes. If I only create new branch from master and try to run tests they are failed too. I've checked requests before and suddenly they were passed. I don't know where to dig in. I think if there is no solution found then I think this request has to be merged.

2024-10-10 13:38 UTC, derrell requested changes

2024-10-10 13:38 UTC, derrell commented on source/class/qx/ui/core/Widget.js
>        if (value === "visible") {
```suggestion
      if (content) {
        if (value === "visible") {
          content.show();
        } else {
          content.hide();
        } // only force a layout update if visibility change from/to "exclude"
      }
```

2024-10-10 13:46 UTC, derrell approved these changes

2024-10-10 13:47 UTC, derrell requested changes
No, that suggestion was supposed to replace both the .show and .hide code

2024-10-10 14:26 UTC, goldim commented
Oh, sorry. Fixed.

2024-10-10 15:26 UTC, derrell approved these changes

2024-10-10 15:40 UTC, cboulanger approved these changes

2024-10-10 18:55 UTC, hkollmann approved these changes

2024-10-12 21:55 UTC, oetiker approved these changes

2024-10-14 09:26 UTC, johnspackman approved these changes

2024-10-14 09:29 UTC, merged