Test client with postMessage transport receiving out-of-order responses
qooxdoo/qooxdoo pull request #10744
Opened 2024-12-28 15:53 UTC by cboulanger

This is an additional test suite for the `qx.io.jsonrpc.Client` using a `postMessage` communication transport, making sure that the communication architecture works as intended. I have also added some assertions for Promises which might or might not be worth adding to the the other assertions in `qx.dev.unit`.

2024-12-28 15:54 UTC, cboulanger commented
Depends on #10742

2024-12-28 20:53 UTC, hkollmann approved these changes

2024-12-29 12:20 UTC, johnspackman approved these changes

2025-01-03 15:52 UTC, oetiker approved these changes

2025-01-03 20:21 UTC, derrell requested changes

2025-01-03 20:21 UTC, derrell commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
Since this is a global change (not sometimes in an app qx.Promise while other times, Promise), wouldn't this best be implemented as an environment setting rather than requiring a code change to call the `useNativePromise` method?

2025-01-04 10:48 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
Thatnk you, that is a good idea. The best solution, however, is if we can fix the underlying problem rather than the symptom - I hope @johnspackman can have a look soon and we can fix `qx.Promise` to not raise the "uncaught promise rejection" error in Firefox in a BC way, then this PR won't be necessary at all.

2025-01-04 14:58 UTC, derrell commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
I'm not convinced there's a problem with `qx.Promise`. In Chrome, in the playground, I get the unhandled rejection error whether using qx promises or native promises. Try pasting this code into the qooxdoo playground. Run it as is, then toggle the value of `native` and run it again. I get the same results either way, and this is in Chrome. 

```javascript
let native = true;
const promiseImpl = native ? Promise : qx.Promise;

(async () => {
	try {
		const promise = new promiseImpl((resolve, reject) => {
			reject(new Error("Rejecting first promise"));
		});
		await new promiseImpl((resolve) => setTimeout(() => {
		        console.log("Resolving second promise")
		        resolve();
		}, 1000));
		await promise;
	} catch (reason) {
		console.log("Caught the first promise rejection");
	}
})();
```

I tried trapping the `unhandledrejection` error as follows, but it is trapped too late:

```javascript
let native = true;
const promiseImpl = native ? Promise : qx.Promise;

globalThis.addEventListener("unhandledrejection", (event) => {
  console.log("Trapped unhandled rejection with error=", event);
  event.preventDefault();
});

(async () => {
	try {
		const promise = new promiseImpl((resolve, reject) => {
			reject(new Error("Rejecting first promise"));
		});
		await new promiseImpl((resolve) => setTimeout(() => {
		        console.log("Resolving second promise")
		        resolve();
		}, 1000));
		await promise;
	} catch (reason) {
		console.log("Caught the first promise rejection");
	}
})();
```

The closest I came to something desirable, was to attach a `catch` handler at promise creation time. This eliminates the error in the console, but also prevents the `catch` of the try/catch from being called. If I rethrow the error, we are, alas, back to the original problem of unhandled rejection.

```javascript
let native = true;
const promiseImpl = native ? Promise : qx.Promise;

(async () => {
	try {
		const promise = new promiseImpl((resolve, reject) => {
			reject(new Error("Rejecting first promise"));
		}).catch((e) => {
		  console.log("Trapped the first promise rejection");
		});
		await new promiseImpl((resolve) => setTimeout(() => {
		        console.log("Resolving second promise")
		        resolve();
		}, 1000));
		await promise;
	} catch (reason) {
		console.log("Caught the first promise rejection");
	}
})();
```

In all cases, this has nothing to do with `qx.Promise`. The results are the same whether using it or native promises.

2025-01-04 16:29 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
There is something wierd going on, though. If you look at the console output in Chrome using the native Promise, the error messages are from `qx.Promise`:

![grafik](https://github.com/user-attachments/assets/54767ede-06c2-4b39-bb96-6ac4f1faba72)

2025-01-04 16:35 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
In contrast, in an `about:blank` window with no qooxdoo present, the console output hides the error message when the promise resolves:

![grafik](https://github.com/user-attachments/assets/dfd65c3a-a82c-491a-985d-06bd29a8c842)

This suggests that this is a qooxdoo issue probably related to `qx.Promise`.

2025-01-04 16:46 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
but we're in a wrong issue, this should be discussed in #9877 or #10739.

2025-01-04 17:27 UTC, johnspackman commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
I agree with @derrell, Im getting the same in Chrome and Firefox and teh same with `qx.Promise` and `Promise`.

I think I have an explanation - I've updated #10739 comment here: https://github.com/qooxdoo/qooxdoo/issues/10739#issuecomment-2571361288

2025-01-04 17:30 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
But did you try this outside the qooxdoo context - because then the behavior is different (see above).

2025-01-04 17:33 UTC, cboulanger commented on source/class/qx/io/jsonrpc/protocol/Request.js
>      }
In contrast to Chrome, in a `about:blank` window in Firefox, we get the promise rejection error:

<img width="715" alt="grafik" src="https://github.com/user-attachments/assets/ea2102fb-483e-4adf-ac2e-3fce4e8f7fd1" />

2025-01-16 07:33 UTC, cboulanger commented
@derrell PR no longer uses native promises, tests pass locally in Firefox and Chrome

2025-01-16 07:39 UTC, cboulanger commented
@johnspackman I provided a [special mixin with asserts to check the state of promises](https://github.com/qooxdoo/qooxdoo/blob/791e8b9f3dd4857c51a7c3b66ceae603f8c0221b/source/class/qx/test/io/MAssert.js) which works with native promises and qx.Promise. I am not familiar enough with the Promises/A+ specification. Is this something that is already possible with qx.Promise, i.e. am I duplicating features, or would it make sense to add this to our assertion library?

2025-01-16 07:59 UTC, cboulanger commented
@hkollmann Still depends on #10739, so only merge afterwards.

2025-01-16 09:44 UTC, johnspackman approved these changes

2025-01-20 20:44 UTC, derrell approved these changes

2025-01-21 09:37 UTC, goldim approved these changes

2025-01-21 09:44 UTC, merged