Added qx.core.MProperty#isPropertyInitialized
qooxdoo/qooxdoo pull request #9183
Opened 2016-09-22 08:04 UTC by mbgonicus

If you got a property `foo` which is not initialized and you call `getFoo()`, you'll get an error that the property is not initialized. You must either enclose it in a try-catch block or set an init value for the property. 

This PR introduces a small function to check if a property is initialized.

2016-09-22 08:15 UTC, level420 approved these changes

2016-09-22 08:16 UTC, level420 commented
LGTM

2016-09-22 08:24 UTC, cajus approved these changes

2016-09-22 08:26 UTC, stahl-riesa commented
IMHO: qx.core.Assert.assertString(prop) should not be called.

2016-09-22 08:30 UTC, level420 commented
@stahl-riesa could you please explain why?

2016-09-22 11:52 UTC, derrell commented
It seems more like a coding error to me if one is getting a property value before setting it (somehow -- through init or a setter). Adding code that /shouldn't/ be needed may not be the best thing to do. Thoughts?

2016-09-22 11:52 UTC, derrell requested changes
See my comment in "Conversation"

2016-09-22 12:03 UTC, mbgonicus commented
@derrell Well, that's one point of view. But in Javascript uninitialized values can always be checked by comparing them to undefined. Qooxdoo breaks with that idiom.

Anyway - with the function, one has the possibility to use uninitialized properties as a valid state. Not allowing that would be a dictation to the user, but I think that is his decision.

All in all its just a short additional function that noone _must_ use.

2016-09-22 12:15 UTC, level420 commented
@derrell even if this method should/would not be used in common scenarios, it allows us to introspect the initialization state of a property through an official API. Sounds useful to me.

2016-09-22 12:37 UTC, derrell commented
I'm not inherently opposed to adding this, but it seems like a rarely used function that just adds bloat and needs to be maintained. We have a large footprint already, so we should carefully consider whether to add new functions (vs. adding classes which are optimized out if not used). Let's just think carefully before adding it. If, after consideration of this, everyone thinks it's still worthwhile, it'll have my vote too.

2016-09-22 12:39 UTC, derrell commented
This function is tiny, so it likely makes little difference whether we add it, but lots of snacks do add up to gaining weight...

2016-09-22 12:41 UTC, johnspackman commented on framework/source/class/qx/core/MProperty.js
> +      qx.core.Assert.assertString(prop);
this should be surrounded by a check for qx.debug

2016-09-22 12:42 UTC, johnspackman requested changes
the qx.core.Assert call should be qx.debug only

2016-09-22 12:43 UTC, stahl-riesa commented on framework/source/class/qx/core/MProperty.js
> +      qx.core.Assert.assertString(prop);
> this should be surrounded by a check for qx.debug

Sorry, thats what I mean!

2016-09-22 12:44 UTC, johnspackman commented
while i agree that uninitialised properties is often a coding design issue, this is not always the case, especially when dealing with arbitrary properties eg via reflection.

2016-09-22 12:46 UTC, mbgonicus commented on framework/source/class/qx/core/MProperty.js
> +      qx.core.Assert.assertString(prop);
fair enough - added the check

2016-09-22 12:46 UTC, mbgonicus commented
qx.debug check is added

2016-09-22 12:50 UTC, johnspackman requested changes
Oops, sorry I didnt spot this earlier Markus - please can you put the check for a getter in the debug also?  As it's also a sanity check

2016-09-22 12:53 UTC, mbgonicus commented
Sure - moved getter check in qx.debug check

2016-09-22 13:10 UTC, johnspackman approved these changes

2016-09-22 15:34 UTC, patrick-fischer-hirschstein approved these changes

2016-09-22 15:38 UTC, derrell approved these changes
Discussion consensus seems to be to include this even though it will likely be unused by most users. It's a tiny function with most elided in build version. Ok with me.

2016-09-26 09:43 UTC, oetiker approved these changes

2016-09-26 10:55 UTC, merged

2016-09-26 10:55 UTC, level420 commented
5 approvals.
merging.
Thank you @mbgonicus