Added "auto select best class" feature
qooxdoo/qooxdoo pull request #9205
Opened 2016-10-06 15:35 UTC by schnepe2

Attempt to fix issue #9193

2016-10-07 06:58 UTC, level420 commented
@schnepe2 Thank you for the PR.

It seems that one of your tests fail constantly on Firefox and Chrome:
```
Chrome 53.0.2785 (Linux 0.0.0) qx.test.data.store Json:testOwnClassWith FAILED
	Not the given class used!: Expected 'qx.test.AB' but found 'qx.data.model.a~b'!
		qx.core.AssertionError.constructor:43:38
		qx.core.Assert.__fail:71:19
		qx.core.Assert.assertEquals:177:33
		qx.type.BaseString.assertEquals:87:22
		anonymous()
		qx.dev.unit.TestResult.run:237:36
		qx.dev.unit.TestCase.resume:100:35
		anonymous()
		qx.event.dispatch.Direct.dispatchEvent:134:34
		wrappedFunction()
		qx.event.Manager.prototype.dispatchEvent()
		qx.event.Registration.fireNonBubblingEvent()
		qx.core.Object.prototype.fireDataEvent()
		qx.data.store.Json.prototype._onSuccess()
		...
```

2016-10-07 07:44 UTC, schnepe2 commented
That "old" test assumes a name for the class that might not be correct.
Strange that this didn't happen on my machine. These tests are head-less, right? I'll see what I have to do to make them pass again.

2016-10-07 09:34 UTC, schnepe2 commented
The test that failed **now** (qx.test.ui.basic Label:testApplyWebFont) is nothing I have done (I think)

2016-10-07 10:10 UTC, level420 commented
@schnepe2 Yes the failing test ```testApplyWebFont``` is failing because of timing issues with travis. See https://github.com/qooxdoo/qooxdoo/issues/9202

But there is another failure here:
```
Running lint...
  - Warning: qx.data.marshal.Json (118, 11): Declared but unused variable or parameter: 'clazz'
Lint warnings are treated as errors! Please fix!
```

2016-10-07 11:36 UTC, schnepe2 commented
About all the tests that failed **now**: I have no idea what happens there.
And unfortunately I have spend more time on this than my boss would allow me to do, so either someone from the core team looks over this or we have to wait until I can steal some more time.

2016-10-07 11:38 UTC, schnepe2 commented
F***k ! I hate the complexity of git! It distracts me from the most obvious things!
I'll try a fix of the fix...

2016-10-07 12:12 UTC, level420 commented
The PR is passing the tests. Start voting/approval.

2016-10-07 12:52 UTC, johnspackman requested changes

2016-10-07 12:52 UTC, johnspackman commented on framework/source/class/qx/data/marshal/Json.js
> +          var className_ = className.replace(/~/g, '"');
Please can you use a different name for the variable - the underscore does not help describe it's purpose, eg `bubbleClassName` ?

2016-10-07 12:52 UTC, johnspackman commented on framework/source/class/qx/data/marshal/Json.js
> -      var hash_ = hash.replace(/"/g, '~');
also please rename the underscores here

2016-10-07 13:39 UTC, schnepe2 commented
@johnspackman Done (not tested of cause!).
Although I think those kind of qooxdoo-internal naming conventions could also have been easily fixed in trunk by you :wink:

2016-10-07 13:49 UTC, oetiker commented
@schnepe2 we do not fix things in master ... changes get into master via PR ... and sure, someone might have done a cleanup PR after merging yours, but then again ... since we have no cleanup crew on staff ...

2016-10-07 14:05 UTC, johnspackman approved these changes

2016-10-07 14:16 UTC, level420 approved these changes

2016-10-07 14:21 UTC, level420 commented
@schnepe2 If I (qooxdoo member) want to change something in master, I have to go through the same procedure you've gone. Create a PR ... Wait for travis runs to be happy ... Start voting ... Wait for comments or change requests ... modify ... sync the PR ...  

The only thing I can do what you can't is merging. But NOT my own PRs.

2016-10-07 14:57 UTC, schnepe2 commented
The corner case of a very simple model (having only one property (like `{a:"a"}`) ) wasn't working
(no glue character to distinguish what kind of class we have)
I therefore changed the "decoration" of the hash by adding a heart prefix ("♥") to model-classes which support the bubble event.

2016-10-08 12:43 UTC, oetiker approved these changes

2016-10-08 12:53 UTC, oetiker commented
@schnepe2 have you seen how many fixes I made to my #9194 PR until it was merged? We do this for two reasons:

a) to ensure that qx master is always clean (to the best of our knowledge), so whenever you pull master you can be sure you get 'the good stuff'

b) often we have to merge the patches for master also with the current stable branch (aka 5.0.x) if every change is one PR, then this is much easier.

2016-10-10 12:16 UTC, cajus approved these changes

2016-10-11 12:27 UTC, merged

2016-10-11 12:27 UTC, level420 commented
4 approvals, more than 2 business days
merging
Thank you @schnepe2