Set qx.ui.table.model.Filtered class as deprecated
qooxdoo/qooxdoo pull request #9206
Opened 2016-10-07 06:45 UTC by woprandi

For https://github.com/qooxdoo/qooxdoo/issues/9204

2016-10-07 09:52 UTC, patrick-fischer-hirschstein approved these changes

2016-10-07 10:15 UTC, johnspackman requested changes
please can you restore the documentation in the comments?  Although this class is being deprecated, there's no need to loose the documentation or otherwise modify it

2016-10-10 07:25 UTC, woprandi commented
@johnspackman you're right

2016-10-10 07:31 UTC, woprandi commented
@johnspackman updated

2016-10-10 07:34 UTC, johnspackman approved these changes
thank you :)

2016-10-10 08:48 UTC, cajus approved these changes

2016-10-10 08:57 UTC, level420 approved these changes

2016-10-10 08:59 UTC, level420 requested changes

2016-10-10 08:59 UTC, level420 commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
The Link to the mozilla developper network does not seem to work

2016-10-10 09:09 UTC, woprandi commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
@level420 it works for me

2016-10-10 09:12 UTC, johnspackman commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
doesnt work for me either

2016-10-10 09:16 UTC, level420 commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
@woprandi the "Objet_globaux" part int he URL seems to be for the french link. My link gets rewritten to start with https://developer.mozilla.org/de/... (german) and is suspect @johnspackman s link gets rewritten to https://developer.mozilla.org/en/ . So wie need the full englisch path in the URL

2016-10-10 09:17 UTC, johnspackman commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
I think you meant https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter - it looks like MDN localises the URLs and unless the locale is specified explicitly it's not reliable

2016-10-10 09:18 UTC, woprandi commented on framework/source/class/qx/ui/table/model/Filtered.js
> + * <a href='http://developer.mozilla.org/docs/Web/JavaScript/Reference/Objets_globaux/Array/filter' target='_blank'>Array.filter</a>
@level420 Oh sorry, I'll fix that

2016-10-10 09:54 UTC, level420 approved these changes

2016-10-10 10:36 UTC, merged

2016-10-10 10:36 UTC, level420 commented
Documentation only fix. Merging.
Thank you @woprandi