completing manual entry on using external JS libs
qooxdoo/qooxdoo pull request #9209
Opened 2016-10-11 21:23 UTC by thron7

This is the second half of the section about integrating external JS libs in the manual, namely creating a wrapping library using `qx.util.DynamicScriptLoader`, as discussed in PR #9181 . (I've also made a minor fix to the class documentation of DynamicScriptLoader.)

Please check for correctness and advise about any necessary corrections.

2016-10-12 06:43 UTC, level420 requested changes

2016-10-12 06:43 UTC, level420 commented on documentation/manual/source/pages/development/using_non_qx_libs.rst
> +                "ponycharts/PonyCharts.js"
I think it should be ```"ponycharts/ponycharts.js"``` to have a consistent naming of the js file.

2016-10-12 06:43 UTC, level420 commented on documentation/manual/source/pages/development/using_non_qx_libs.rst
> +              console.log("all scripts have been loaded!");
A code fragment or a call to something like ```initializePonyCharts``` could be placed here to show the reader that this is the right place to do some post loading tasks.

2016-10-12 08:02 UTC, oetiker requested changes

2016-10-12 08:02 UTC, oetiker commented on documentation/manual/source/pages/development/using_non_qx_libs.rst
that would only be necessary if the ponycharts_lib was a qooxdoo contrib ... so I guess this step could be dropped

2016-10-12 10:51 UTC, thron7 commented on documentation/manual/source/pages/development/using_non_qx_libs.rst
> +                "ponycharts/PonyCharts.js"
Yep.

2016-10-12 11:07 UTC, oetiker approved these changes

2016-10-12 11:44 UTC, derrell approved these changes

2016-10-13 04:30 UTC, level420 approved these changes

2016-10-13 04:32 UTC, merged

2016-10-13 04:32 UTC, level420 commented
Documentation only PR. 3 approvals 
Merging
Thank you @thron7