use the correct start time for animation sequences
qooxdoo/qooxdoo pull request #9226
Opened 2016-11-09 10:01 UTC by peuter

The start time for an animation sequence should be based on performance.timing.navigationStart + performance.now() and not Date.now() (if performance api is available)

As the performance API says performance.now() is constantly increasing (independent from changes to system tiime) while the browser is active.It does not increase during browser suspension. So e.g. after the browser has been suspended for 10s Date.now() would be 10s ahead performance.timing.navigationStart + performance.now() and the animation sequence would start with a 10s delay with the current implementation.

And I replaced `+(new Date())` with `Date.now()` within this fix.

2016-11-09 10:05 UTC, cajus approved these changes
Looks familiar ;-)

2016-11-09 10:23 UTC, level420 requested changes

2016-11-09 10:23 UTC, level420 commented on framework/source/class/qx/bom/AnimationFrame.js
> +      var start = (window.performance && window.performance.now) ? (performance.now() + qx.bom.AnimationFrame.__start) : Date.now();
I'm not shure, but this should be tested against Internet Explorer which tends to fail on such tests like 
```javascript
(window.performance && window.performance.now)
```
vs.
```javascript
("performance" in window ...
```

I think it whould be better to have a ```qx.core.Envorinment.get("performance.timer")``` to check against, which also may be handy in other situations.

2016-11-09 10:35 UTC, level420 commented on framework/source/class/qx/bom/AnimationFrame.js
> +      var start = (window.performance && window.performance.now) ? (performance.now() + qx.bom.AnimationFrame.__start) : Date.now();
Hmm. I see that the original code uses the check window.performance in the defer section, so it should be safe then.

@peuter do you think the  qx.core.Environment.get("performance.timer") is worth it?

2016-11-09 10:36 UTC, cajus commented on framework/source/class/qx/bom/AnimationFrame.js
> +      var start = (window.performance && window.performance.now) ? (performance.now() + qx.bom.AnimationFrame.__start) : Date.now();
`performance.timer` is intended to be used for performance monitoring, only. I guess the only reason why it is used here (the only location in the complete framework) is that the animation frame callback gets a `DOMHighResTimeStamp` parameter. Not sure if it is usable for something else, though. I'm wondering what for you need a 5µ resolution an a web platform.

2016-11-09 10:39 UTC, level420 commented on framework/source/class/qx/bom/AnimationFrame.js
> +      var start = (window.performance && window.performance.now) ? (performance.now() + qx.bom.AnimationFrame.__start) : Date.now();
@peuter @cajus. I'm convinced, maybe besides of the test which should be (I think)

```javascript
(window.performance && performance.now)
```
to get par with the test in the defer section.

2016-11-09 10:42 UTC, level420 approved these changes

2016-11-09 10:53 UTC, level420 commented
@peuter I don't know if this is relevant anymore, but using Date.now will break compatibility for some ancient browsers. See https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/now

2016-11-09 10:54 UTC, peuter commented
@level420 Qooxdoo has its own polyfill for `Date.now()` which is `+(new Date())` by the way.

2016-11-09 10:55 UTC, level420 commented
Cool! then I'm quiet now ;-)
Looks good.

2016-11-09 11:05 UTC, johnspackman approved these changes

2016-11-09 11:05 UTC, johnspackman approved these changes

2016-11-09 13:56 UTC, level420 commented
Removed the release_5_0_2 milestone, as it is no bug fix, more an enhancement.

2016-11-09 14:05 UTC, peuter commented
This is a bugfix, no enhancement.

2016-11-11 13:48 UTC, merged

2016-11-11 13:48 UTC, level420 commented
2 approvals. more than 2 business day. merging
Thank you @peuter