Fix scroll momentum behaviour
qooxdoo/qooxdoo pull request #9234
Opened 2016-11-22 14:11 UTC by peuter

With current implementation you cannot continue (or change the direction)  a momentum scrolling, it always stops on pointerdown. This PR only stops the momentum scroll but does not cancel the gesture. It also stops the currently running momentum scroll when a new one ist started.

As an addition i stumbled open the unused method `isBelowTapMaxDistance` while analyzing the problem, this PR removes it (there is a `_isBelowTapMaxDistance` method anyway).

2016-11-22 14:29 UTC, cajus approved these changes

2016-11-22 16:42 UTC, oetiker requested changes

2016-11-22 16:42 UTC, oetiker commented on framework/source/class/qx/event/handler/GestureCore.js
> -
this is a public method so even if it is not used internally you would have to deprecate it prior to removal

2016-11-22 20:27 UTC, hkollmann commented on framework/source/class/qx/event/handler/GestureCore.js
> -
You are right. But the implemention can not work. TAP_MAX_DISTANCE returns an object  )-:

2016-11-22 20:30 UTC, hkollmann commented on framework/source/class/qx/event/handler/GestureCore.js
> -
You are right. But the method will not work because TAP_MAX_DISTANCE is an object.

2016-11-23 06:55 UTC, peuter commented on framework/source/class/qx/event/handler/GestureCore.js
> -
And `this._calcDelta` does not exist.

2016-11-23 07:23 UTC, oetiker commented on framework/source/class/qx/event/handler/GestureCore.js
> -
ah ... ok ... so no one could have used it anyway ... ok

2016-11-23 07:23 UTC, oetiker approved these changes

2016-11-23 11:26 UTC, johnspackman approved these changes

2016-11-23 12:35 UTC, level420 approved these changes

2016-11-25 07:50 UTC, merged

2016-11-25 07:50 UTC, level420 commented
4 approvals, more than 2 business days.
merging
thank you @peuter