fix logger to not use the $$hash value when this object has not bee…
qooxdoo/qooxdoo pull request #9236
Opened 2016-11-28 08:29 UTC by peuter

…n registered in the Registry.

This fixes the problem, that the logging object was not shown in the log string since the new automatic memory management feature has been introduced.

2016-11-28 08:38 UTC, level420 requested changes
It seems that this fix let's a test fail in travis:

```
Chrome 55.0.2883 (Linux 0.0.0) qx.test.log Logger:testContextObject FAILED
	Expected '6676-1' but found ''undefined''!
		qx.core.AssertionError.constructor:43:38
		qx.core.Assert.__fail:71:19
		qx.core.Assert.assertEquals:177:33
		qx.type.BaseString.assertEquals:87:22
		qx.test.log.Logger.testContextObject:100:12
		qx.dev.unit.TestFunction:118:23
		qx.dev.unit.TestResult.run:237:36
		qx.dev.unit.TestFunction.run:115:18
```

Wouldn't it be better to fix this where the $$hash gets resolved?

... or if not, the test ```testContextObject```has to  be modified to use a class which implements ```qx.core.IDisposable```

2016-11-28 08:57 UTC, peuter commented
It is better to not use the $$hash, when is cannot be resolved anyway. You cannot fix this where $$hash gets resolved because the needed ' clazz' information is missing there, because the Logger either stores the $$hash or the `clazz` but not both.

I will take a look at the test, bit I think the test needs to be fixed too.

2016-11-28 09:03 UTC, level420 commented
@peuter OK. Understood. Then a fixed test would be good. Thank you!

2016-11-28 10:02 UTC, level420 requested changes

2016-11-28 10:02 UTC, level420 commented on framework/source/class/qx/test/log/Logger.js
> +      qx.Class.define("test.DisposableObject", {
could you please undefine the class via ```qx.Class.undefine``` to prevent pollution with test classes? Thank you.

2016-11-28 10:20 UTC, level420 approved these changes

2016-11-28 12:25 UTC, cajus approved these changes

2016-11-28 12:28 UTC, derrell commented
I'm not convinced this is an appropriate change. We have a means, even with automaticMemoryManagement turned on, to get a hash code, via toHashCode(). Should we not simply call that function to obtain the hash code, for better logger debugging, rather than excluding the hash code altogether?

2016-11-28 12:34 UTC, peuter commented
The problem is, that the hashcode is used to retrieve the Object here: https://github.com/qooxdoo/qooxdoo/blob/0bcb969/framework/source/class/qx/log/appender/Util.js#L175

And that does not work when automaticMemoryManagement is turned on, leading to a missing classname in the log message.

2016-11-28 12:49 UTC, derrell commented
The hash code is very useful in debugging, particularly when the same message is printed numerous times for different objects. How about calling qx.core.ObjectRegistry.register() in this patch so that the normal fromHashCode is available at line Util.js#L175?

2016-11-28 12:54 UTC, peuter commented
Would't you loose the benefits from the memorymanagement, when you register all your logged objects?
I would prefer to add the hash value to the clazz structure if available.

2016-11-28 12:58 UTC, derrell commented
For those few objects, used for debugging rather than production, I don't see a problem with losing the benefits of the memory management change. It wouldn't be for all objects; only those used in Logger calls. It appears, however, that all objects have a hash code, assigned either via register() or via toHashCode() in qx.core.Object's constructor. The Logger output, therefore, can use entry.clazz.toHashCode() to retrieve that hash code in the output if memory management is in effect.

2016-11-28 13:10 UTC, johnspackman commented
The automatic memory management just means that the object is not logged in a central list, so the hash code is important because it could be used as an index in other lookups.  IMHO the logger should store the hashcode always, and then leave it up to the appender to try and resolve it; this would allow the application to add custom appenders to resolve custom hashcode lookups.

I would definitely not call `.register` in the Logger because it means behaviour of the objects would change depending on the debug level in use - for example, my apps download a set of filters for Logger on a per-user basis so that users with issues can be configured to have their log output increased and uploaded to the server.  IE the logger is used in production; it wouldnt be good for the changed configuration of logging to change the memory management.

Eg teh code should be:

```
        if (object.$$hash !== undefined) {
          entry.object = object.$$hash;
        }
        if (object.$$type) {
          entry.clazz = object;
        } else if (object.constructor) {
          entry.clazz = object.constructor;
        }

```

2016-11-28 13:36 UTC, peuter commented
I agree with @johnspackman to not use `register`in the Logger. I will change my PR according to his suggestion and let the appender handle all cases to provide the hash code information even if memory management is enabled.

2016-11-28 13:38 UTC, derrell commented
Sounds fine to me. As long as the appender displays a hash code for each object, I'm happy.

2016-11-30 15:27 UTC, derrell approved these changes

2016-12-01 10:19 UTC, merged

2016-12-01 10:19 UTC, level420 commented
3 approvals. more than 2 business days since labeled voting.
merging.
thank you @peuter