add resetSource method to qx.html.Label as it is used by qx.ui.basic.…
qooxdoo/qooxdoo pull request #9239
Opened 2016-11-30 08:35 UTC by peuter

…Image when using font icons.

This PR adds the missing method which is used here:
https://github.com/qooxdoo/qooxdoo/blob/0bcb969/framework/source/class/qx/ui/basic/Image.js#L877

2016-11-30 10:20 UTC, cajus requested changes
Can you add a test for this scenario?

2016-11-30 10:20 UTC, cajus approved these changes
Ah. I've been too slow ;-)

2016-11-30 10:25 UTC, johnspackman approved these changes

2016-11-30 11:03 UTC, level420 approved these changes

2016-11-30 11:58 UTC, derrell approved these changes

2016-12-01 12:32 UTC, oetiker approved these changes

2016-12-01 12:34 UTC, merged

2016-12-01 12:34 UTC, cajus commented
Thanks @peuter.