stop momentum scrolling when the window object is gone
qooxdoo/qooxdoo pull request #9243
Opened 2016-12-01 14:52 UTC by peuter

when you close e.g. a dialog while its content is scrollign with a momentum, the roll event gets fired on an non existing element, which leads to an error.

This fix stops the momentum scrolling when the internal `__window` object is gone.

2016-12-01 14:56 UTC, level420 approved these changes

2016-12-01 14:59 UTC, level420 requested changes

2016-12-01 14:59 UTC, level420 commented on framework/source/class/qx/event/handler/GestureCore.js
>          delete this.__stopMomentum[oldTimeoutId];
Hmmm... couldn't find where ```this.__window``` is declared or initialized.

2016-12-01 15:06 UTC, peuter commented on framework/source/class/qx/event/handler/GestureCore.js
>          delete this.__stopMomentum[oldTimeoutId];
It is declared in `qx.event.handler.Gesture` which is a subclass of `qx.event.handler.GestureCore`, but as I am writing this I wonder if it is possible to access a private member from a subclass?

If not I guess `__window` needs to be changed to `_window`.

2016-12-01 15:11 UTC, derrell commented on framework/source/class/qx/event/handler/GestureCore.js
>          delete this.__stopMomentum[oldTimeoutId];
It is not possible, in the `build`  version, to access privates from other classes.

2016-12-01 15:19 UTC, level420 commented on framework/source/class/qx/event/handler/GestureCore.js
>          delete this.__stopMomentum[oldTimeoutId];
... or you need a getter 
```javascript
  getWindow : function() {
    return this.__window;
  },
```

2016-12-01 15:20 UTC, level420 commented on framework/source/class/qx/event/handler/GestureCore.js
>          delete this.__stopMomentum[oldTimeoutId];
See also the failing travis job
```
Running lint...
  - Warning: qx.event.handler.GestureCore (425, 99): Using an undeclared private class feature: '__window'
Lint warnings are treated as errors! Please fix!
```

2016-12-01 15:37 UTC, level420 approved these changes

2016-12-02 07:29 UTC, cajus approved these changes

2016-12-04 10:07 UTC, zaucker approved these changes

2016-12-06 06:32 UTC, merged

2016-12-06 06:33 UTC, cajus commented
Merging. Two businessdays and no dissenting votes. Thank you @peuter.