remove context parameter
qooxdoo/qooxdoo pull request #9292
Opened 2017-03-02 09:32 UTC by peuter

Something I just stumbled upon: I think this is some kind of copy & paste error which causes the native event listener to be added in the capturing phase. If this is a wanted behaviour, we should change the last parameter from `this` to `true`. Otherwise remove it as suggest in this PR.

I don't really know how much impact this change would have on existing applications, so this change needs to be discussed first.

2017-03-02 10:18 UTC, level420 commented
As `this` is defined in https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/handler/Gesture.js#L132 and https://github.com/qooxdoo/qooxdoo/blob/68a9fd0/framework/source/class/qx/bom/Event.js#L87 ``!!useCapture`` is used, I assume the correct fix would be to change the fix to:
```javascript
      qx.bom.Event.addNativeListener(data.target, data.type, this.__fireRollWrapped, true);
```

2017-03-02 10:35 UTC, peuter commented
Yes as I said, using `true` would fix this without changing the behaviour, but I think this behaviour has been introduced by accident and not on purpose.

2017-03-02 10:57 UTC, level420 commented
It's in there from start: https://github.com/qooxdoo/qooxdoo/commit/56a4840c23c312ad57670f361447c16dacd2242b#diff-89346d402646fd82486d8a77f9598e28

2017-03-02 11:13 UTC, level420 commented
We could introduce tighter checking on parameter 4 of `qx.bom.Event.addNativeListener` like this:
```javascript
if(useCapture !== undefined && useCapture !== false, && useCapture !== true) {
  // e.g. throw an exception
}
```
this way we could detect such situations.

2017-03-09 08:14 UTC, level420 requested changes
I currently don't have the use case for gestures and not the time to investigate what the possible negative effect of interpreting `this` as `true` for useCapture may be.
Therefore I think the fix for now should be to replace `this` by `true`.
Additionally It simply seemed to work a long time as this was introduced nearly 3 years ago.

2017-03-09 09:10 UTC, johnspackman commented
I agree it looks like a typo, but if we don't have any tests/experience that show that a falsey-value works fine, and we do not have a case where a truthy-value is causing a problem, then it's difficult to justify making it something other than `true`.

2017-03-10 10:02 UTC, level420 commented
@peuter Just "highjacked" your PR and replaced `this` by `true`.

2017-03-10 10:02 UTC, level420 approved these changes

2017-03-10 10:19 UTC, johnspackman approved these changes

2017-03-10 11:02 UTC, peuter commented
Didn't know that is even possible. Just imagine that I did it myself and we do not hurt your contribution rules ;-)

2017-03-10 12:31 UTC, derrell approved these changes

2017-03-10 13:07 UTC, peuter commented
Maybe we should add a comment to the changed line, that the event is added to the capturing phase for historical reasons and a link to this ticket?

2017-03-10 13:36 UTC, oetiker approved these changes

2017-03-10 13:39 UTC, cajus approved these changes

2017-03-10 14:13 UTC, johnspackman approved these changes

2017-03-10 14:24 UTC, level420 approved these changes

2017-03-13 07:53 UTC, merged

2017-03-13 07:54 UTC, level420 commented
5 approvals. 
merging.
Thank you @peuter