bug fix for complex regex
qooxdoo/qooxdoo pull request #9307
Opened 2017-03-30 10:50 UTC by hkollmann

if you set the filter to an complex regex like `^(\+|-)?\d*$` validating never stops.
This commit fixes this issue and adds some test cases.

I seperated the the code for validating in `_onHtmlInput` to an own function `_validateInput`. This function could be tested easily.

2017-04-03 07:05 UTC, level420 commented
@hkollmann it seems that the travis job is currently unable to load/start chrome unstable

2017-04-03 07:06 UTC, level420 commented
@hkollmann could you please open an issue regarding the failing chrome unstable travis job? thank you.

2017-04-03 13:00 UTC, derrell commented
I'm not convinced this is a valid issue. The `filter` property is supposed to be a regexp that has the valid characters for the field:

```
    /**
     * RegExp responsible for filtering the value of the textfield. the RegExp
     * gives the range of valid values.
     * The following example only allows digits in the textfield.
     * <pre class='javascript'>field.setFilter(/[0-9]/);</pre>
     */
```

so any filter regexp that contains `^` and/or `$` is providing "bad" input to the filter property. I believe that as designed, the filter regexp must evaluate to a single character. It must not have any relative positions.

In fact, the code could really be simplified to something like this entirely untested code:
```
var filter = this.getFilter();
filter = new RegExp("^(" + filter.toString() + ")+$");
if (! value.match(filter))
{
    this.getContentElement().setValue(this.__oldInputValue);
}
```

So the question here, is do we want to extend the functionality, and is it entirely backward compatible?

2017-04-03 13:05 UTC, oetiker commented
I would go even further and not even anchor the filter ... let the users choose how they want to shoot themselves ...

2017-04-04 15:34 UTC, hkollmann commented
The most Intention for this fix is that the check functions returns even if the filter is not correct.
Before you get an endless Loop.
I agree with @derrell  that the Intention was a list of allowed characters. But it should be return in all cases.

Yes it's backward compatible - that's the reason why i added some unit testing.

2017-04-04 16:12 UTC, derrell commented
Point taken, that it should never go into an infinite loop. Ok, let's make sure it can work with a regexp that doesn't match only a single character. I don't understand how it works. Does it work if the regexp is `/xy/` (i.e., the only valid complete input is the string `xy`) and the first character, `x` is entered in the field? If it does, then I need an explanation of your new validation function because I don't see it...

2017-04-04 19:26 UTC, hkollmann commented
Validation function is not new. It's the old one with a little fix to go out the loop.
new is that it's an seperate function copied from the old _onHtmlInput function so that the validate could be unit tested.

2017-04-05 12:04 UTC, derrell commented
Yes, I understand. I'm just trying to ascertain if this fix, which is intended to change the behavior (filter regexp matches a single character -> filter regexp matches more than one character) works in all cases, or only with some regexps. If it works in all cases, I'm all for this. If only certain regexps will work with it, then I think we need to consider it more. If the regexp is `/^xy$/` then what happens when the user enters `x`? `y`? `xy` (if it's possible)?

I don't disapprove of this concept at all; I'm just trying to ensure that it doesn't fix the infinite loop problem, allowing regexps which aren't intended, but then not work with other regexps. In that case, it might be better to just document the fact that the filter regexp **must** match only a single character and attempting to do otherwise is at their own peril.

2017-04-05 20:31 UTC, hkollmann commented
what's about writing a test case for the expressions you have problems with? One benefit of the patch is that this is possible now.
Any suggestions?

2017-04-07 06:45 UTC, level420 commented on framework/source/class/qx/ui/form/AbstractField.js
>        {
@hkollmann could you please explain why the if condition changed from `if(this.getFilter() != null)` to `if(fireEvents)`?

2017-04-07 08:45 UTC, hkollmann commented on framework/source/class/qx/ui/form/AbstractField.js
>        {
you are right. Should be `if (fireEvents && (this.getFilter() != null)`

2017-04-07 13:49 UTC, level420 approved these changes

2017-04-18 06:55 UTC, hkollmann commented
Could we get a decision about this? Thank's!

2017-04-18 07:20 UTC, oetiker requested changes
yes ... the fix seems fine ... although the whole thing works a lot different from what I thought It would work ... maybe the description should be changed too:

> RegExp responsible for filtering the value of the textfield. the RegExp gives the range of valid values. The following example only allows digits in the textfield.

sounds not like what is happening here ... I get the impressen the person who did the first implementation did not entirely grasp how regexps work ... 

maybe change the documentation to 

>RegExp responsible for filtering the value of the textfield. Note, that the regexp specified is applied to each character in turn, NOT to the entire string. So only regular expressions matching a single character make sense in the context.

2017-04-18 07:55 UTC, hkollmann commented
>> I get the impressen the person who did the first implementation did not entirely grasp how regexps work ...

That was my Impression too,

2017-04-18 08:06 UTC, oetiker approved these changes

2017-04-18 08:07 UTC, oetiker requested changes

2017-04-18 08:07 UTC, oetiker commented on framework/source/class/qx/ui/form/AbstractField.js
> +	 *       single character make sense in the context.
hmmm it seems something is out of shape with the indentation here ...

2017-04-18 09:08 UTC, level420 commented
@oetiker fixed indention

2017-04-18 11:09 UTC, oetiker approved these changes

2017-04-20 02:48 UTC, derrell approved these changes
With the addition of the Note in the documentation, I'm find with this. Thanks.

2017-04-20 06:38 UTC, merged

2017-04-20 06:38 UTC, level420 commented
3 approvals, more than 2 busines days
merging
thank you @hkollmann