#9331 fix focus should return textfield child control
qooxdoo/qooxdoo pull request #9333
Opened 2017-05-16 14:01 UTC by ronkie

Method __fixFocus should return textfield child control for Combo, Spinner and DateField.

This way compound input control still stays active after mouse up happens outside of it (same as simple text and textarea controls), and keypress is fired correctly.

2017-05-17 07:34 UTC, oetiker requested changes

2017-05-17 07:34 UTC, oetiker commented on framework/source/class/qx/event/handler/Focus.js
> +          return this.__getCorrectFocusTarget(target);
hmmm does this actually get called in the right context ?

couldn't you just write:

`mshtml: this.__getCorrectFocusTarget,`

2017-05-17 07:34 UTC, oetiker commented on framework/source/class/qx/event/handler/Focus.js
same queston as above

2017-05-17 10:35 UTC, ronkie commented on framework/source/class/qx/event/handler/Focus.js
> +          return this.__getCorrectFocusTarget(target);
Hi! I think I could :) Is it the only adjustment to the code? If so, I agree.

2017-05-17 10:35 UTC, ronkie commented on framework/source/class/qx/event/handler/Focus.js
Yes, same here.

2017-05-17 12:19 UTC, oetiker commented on framework/source/class/qx/event/handler/Focus.js
> +          return this.__getCorrectFocusTarget(target);
well from me ... there may be more ... as others review :)

2017-05-26 06:21 UTC, level420 commented
@ronkie thank you for your PR. Any chance to incorporate the changes requested by @oetiker ?

2017-05-30 09:22 UTC, ronkie commented
Hi @level420, @oetiker,

I agree with the changes by @oetiker , but I only see link "See review", but not "Approve" or something like that. I am new to github and maybe I am missing something.

If it is possible, please integrate them, or let me know how I can do that :)

Regards,
Veronika.

2017-05-30 09:32 UTC, johnspackman commented
Hi Veronika, you just modify the code locally (in your original branch), commit it and push it - so long as it's all in the original branch, those changes will be automatically pushed through to the PR

2017-05-30 15:12 UTC, oetiker commented
@ronkie these 'request changes' are just that ... 'requests FOR YOU to change your PR' :) ... as @johnspackman just make the changes in your checkout, and push again ...  then this PR will automatically update itself and reflect your changes.

2017-06-01 11:34 UTC, ronkie commented
Thanks @johnspackman, @oetiker for the explanations, I've made the changes and pushed them, hope I did everything correct.

2017-06-01 12:59 UTC, level420 approved these changes

2017-06-01 13:00 UTC, level420 commented
@ronkie looks good! Thank you!

2017-06-01 13:05 UTC, patrick-fischer-hirschstein approved these changes

2017-06-01 13:44 UTC, cboulanger approved these changes

2017-06-02 11:16 UTC, johnspackman approved these changes

2017-06-02 13:10 UTC, oetiker approved these changes

2017-06-06 07:29 UTC, merged

2017-06-06 07:29 UTC, level420 commented
4 approvals. more than 2 business days.
merging
thank you @ronkie

2017-06-07 21:04 UTC, valette commented
With this commit, I'm getting an error ( with chrome, linux ) each time the mouse button is released (mouseup) : 
```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at wrapper.__fixFocus (GlobalError.js:131)
    at wrapper.webkit (Focus.js:1031)
    at wrapper.__onNativeMouseUp (GlobalError.js:131)
    at HTMLDocument.<anonymous> (Function.js:337)
qx.event.handler.Focus.prototype.__fixFocus() @ GlobalError.js:131
webkit @ Focus.js:1031
qx.event.handler.Focus.prototype.__onNativeMouseUp() @ GlobalError.js:131
(anonymous) @ Function.js:337
```

2017-06-09 14:03 UTC, level420 commented
@valette thank you for your bug report. I've created a followup PR #9347