fixes for qxcompiler
qooxdoo/qooxdoo pull request #9346
Opened 2017-06-02 16:14 UTC by johnspackman

These are a few minor fixes for qxcompiler

2017-06-03 11:04 UTC, oetiker requested changes

2017-06-03 11:04 UTC, oetiker commented on framework/source/class/qx/core/Object.js
> + * @use(qx.Promise)
this causes

```
 - Warning: Detected circular dependency between: qx.Promise and qx.core.Object
```
when trying the build with the generator. see travis!

2017-06-04 10:51 UTC, johnspackman commented
Darn, that change to qx.core.Object shouldn't have been in there at all - reverted

2017-06-06 07:28 UTC, level420 approved these changes

2017-06-06 07:30 UTC, oetiker approved these changes

2017-06-06 08:05 UTC, cboulanger approved these changes

2017-06-06 09:19 UTC, patrick-fischer-hirschstein approved these changes

2017-06-06 11:17 UTC, derrell approved these changes

2017-06-13 08:06 UTC, merged

2017-06-13 08:06 UTC, level420 commented
more than 2 business days. 4 approvals 
merging
thank you @johnspackman