Strict mode compliance
qooxdoo/qooxdoo pull request #9382
Opened 2017-08-24 16:43 UTC by johnspackman

Various minor fixes for strict mode compliance, IE remove references to `arguments.callee` and `arguments.caller`

2017-08-24 16:53 UTC, derrell requested changes

2017-08-24 16:53 UTC, derrell commented on framework/source/class/qx/test/Bootstrap.js
> +            var ret = qx.test.Bmw.prototype.stopEngine.base.call();
Is this the same as the following?
```
var ret = this.base(arguments);
```

.call() with no first argument means that the context is explicitly excluded. That sounds wrong to start with, unless there is no reference to `this` in the `...stopEngine.base` method...

2017-08-24 16:53 UTC, derrell commented on framework/source/class/qx/test/Bootstrap.js
> +            var ret = qx.test.Bmw.prototype.stopEngine.base.call();
Similarly, elsewhere in here. This is *really* old code you're modifying here.

2017-08-24 17:08 UTC, johnspackman commented on framework/source/class/qx/test/Bootstrap.js
> +            var ret = qx.test.Bmw.prototype.stopEngine.base.call();
yes, really old - I guess this is why it was doing some slightly strange things to accomplish the tests; I was aiming to make the smallest changes and just translate the syntax, but I agree it doesn't make it any clearer!  I'll change it

2017-08-24 17:16 UTC, derrell requested changes

2017-08-24 17:16 UTC, derrell commented on framework/source/class/qx/util/Function.js
>          // to have access inside the interval method
This comment is now incorrect

2017-08-24 17:38 UTC, cboulanger approved these changes

2017-08-24 18:14 UTC, derrell approved these changes

2017-08-25 05:03 UTC, oetiker approved these changes

2017-08-27 19:13 UTC, cajus approved these changes

2017-09-03 20:04 UTC, merged