This disables the unit test that causes Travis to break on Headless Chrome
qooxdoo/qooxdoo pull request #9431
Opened 2017-11-29 19:08 UTC by johnspackman

This is an ugly solution but it seems fruitless to constantly get notification of failed builds because of this one test on one browser.  The problem is isolated to one test case only and it is in a section of code that is very stable

2017-11-29 19:17 UTC, cajus commented
I'm already working on a PR for that. It also moves the tests to *saucelabs*, so that we can test against more browsers on more platforms. Currently fighting against travis to make it play nicely.

2017-11-29 19:36 UTC, cboulanger submitted a review, later dismissed

2017-11-29 19:47 UTC, derrell submitted a review, later dismissed
This LGTM, but it sounds like @cajus has a more complete fix to use instead?

2017-11-29 20:14 UTC, johnspackman commented
I'm more than happy to withdraw this, how far away do you think you are from a full solution @cajus ?  I just had a failure report for editing `.github/CODEOWNERS`, would it be worth committing this in the short term and reverting it with the switch to saucelabs?

2017-11-29 20:21 UTC, cajus commented
@johnspackman I hope to get it running soon. But I'm happy with applying this one as a quicky, too.

2017-11-30 07:52 UTC, hkollmann requested changes
I would prefer the Change cajus suggested

2017-11-30 11:41 UTC, hkollmann approved these changes

2017-11-30 11:49 UTC, cajus approved these changes

2017-11-30 16:22 UTC, derrell approved these changes

2017-11-30 18:16 UTC, level420 approved these changes

2017-12-01 08:04 UTC, cboulanger approved these changes

2017-12-01 08:19 UTC, hkollmann commented
5 approvals, merged

2017-12-01 08:21 UTC, level420 commented
@hkollmann thank you for merging. In this case please also close the PR via "Close and comment". Thank you.

2017-12-01 08:24 UTC, oetiker approved these changes

2017-12-01 08:49 UTC, merged