Add needed packages doc
qooxdoo/qooxdoo pull request #9440
Opened 2017-12-01 21:16 UTC by hkollmann

during setup an enviroment with Windows 10 ubuntu i documented the needed packages for the build process.

2017-12-02 20:42 UTC, cboulanger approved these changes

2017-12-04 07:08 UTC, level420 approved these changes

2017-12-04 07:22 UTC, cajus requested changes
This is very windows specific stuff and I guess it's not correct, too. At least the qx toolchain is incompatible with python 3.6. It needs python 2.x. In this case (and in case of ordinary ubuntu systems) you don't need any PPAs installed. So that is misleading.

Additionally building releases is done automatically and the documentation does not reflect what we do in the moment. I'd drop it completely.

2017-12-04 08:20 UTC, cboulanger requested changes
I defer to @cajus' judgement, since I don't know enough about the matter.

2017-12-04 11:49 UTC, hkollmann commented
I will close this PR and open a new one in https://github.com/qooxdoo/qx-dev-manual special for the requierements of an ubuntu subsystem in Windows 10. Would this be ok?
Whe should really delete the admin docs here and maintenance them only in qx-dev-manual

2017-12-04 11:49 UTC, closed without merging