Remove texlive and introduce 'git fetch' limit
qooxdoo/qooxdoo pull request #9468
Opened 2017-12-18 09:14 UTC by cajus

This is an attempt to reduce the required *travis* disk space on the deploy job.

2017-12-18 09:18 UTC, johnspackman submitted a review, later dismissed

2017-12-18 09:21 UTC, cboulanger submitted a review, later dismissed

2017-12-18 09:25 UTC, level420 submitted a review, later dismissed

2017-12-18 12:06 UTC, derrell submitted a review, later dismissed

2017-12-18 13:06 UTC, hkollmann requested changes
line 77, git clone -q git@github.com:qooxdoo/qooxdoo.github.io.git tmp is a candidate for --depth either....

2017-12-18 13:37 UTC, cajus commented
@hkollmann definitely.

2017-12-18 13:43 UTC, hkollmann approved these changes

2017-12-18 16:15 UTC, derrell approved these changes
See my comment on line 77 (also applies to line 35). If it's just cruft, we should create a separate PR to remove it.

2017-12-18 16:15 UTC, derrell commented on .travis/deploy
> +git clone --depth 10 -q git@github.com:qooxdoo/qooxdoo.github.io.git tmp
I know what it means, but in this particular case, what are these `--depth` options accomplishing? What's so far down the tree that we don't need it, and if we don't need it, why is it there?

2017-12-20 16:02 UTC, cboulanger approved these changes

2017-12-20 16:04 UTC, oetiker approved these changes

2017-12-20 16:28 UTC, johnspackman approved these changes

2017-12-20 20:57 UTC, hkollmann commented
3 days, 5 approvals. Thanks @cajus

2017-12-20 20:58 UTC, merged

2017-12-20 22:20 UTC, zaucker reviewed
Sounds ok to me.