Improved error messages when databinding fails on missing target setter
qooxdoo/qooxdoo pull request #9480
Opened 2018-01-14 12:12 UTC by cboulanger

This has bugged me for years, but I never got around fixing it. During a binding, if a target setter method is missing, it will throw a cryptic error message (`target["set" + qx.lang.String.firstUp(lastProperty)] is not an object`, with no indication where and why this error was thrown. This PR provides a more descriptive error message which allows to search the code for databinding involving the target object and property.

2018-01-14 14:55 UTC, cajus commented
Looks like the try/catch breaks validation in combination with the `onSetFail` option.

2018-01-14 14:57 UTC, cajus requested changes
See comment. The `throw Error()` does not respect errors that get catched later on (i.e. ValidationError).

2018-01-14 15:33 UTC, cboulanger commented
Doesn't the option `onSetFail` refer to setting a _value_? This concerns the process of setting up the _binding_, so I wouldn't expect `onSetFail` to report the error. The problem,too, is that at that point, the value of the `option` parameter is unavailable, one would have to store it in a private property, but that looks like a hack.

2018-01-14 15:35 UTC, cboulanger commented
... the same seems to concern Validation errors - it looks to me that at the time of setting up the binding, values aren't validated, but only at the time of the actual value transfer. Or am I missing something here?

2018-01-14 19:33 UTC, cboulanger commented
One test fails on an issue unrelated to the PR: https://travis-ci.org/qooxdoo/qooxdoo/jobs/328772627#L6874

2018-01-14 21:37 UTC, hkollmann commented
Sometimes a restart helps!

2018-01-14 21:37 UTC, hkollmann approved these changes

2018-01-14 21:40 UTC, derrell approved these changes

2018-01-15 07:56 UTC, cajus approved these changes

2018-01-15 09:01 UTC, oetiker approved these changes
great!

2018-01-15 09:07 UTC, johnspackman approved these changes

2018-01-15 16:37 UTC, level420 approved these changes

2018-01-15 17:06 UTC, merged

2018-01-15 17:07 UTC, johnspackman commented
6 approvals, merging, thank you @cboulanger