Fix for #9524: fix recursive included decorator style propagation
qooxdoo/qooxdoo pull request #9525
Opened 2018-04-23 15:37 UTC by level420

Replaced the faulty recursive decorator include algorithm.

See #9524.

2018-04-23 16:05 UTC, cboulanger submitted a review, later dismissed

2018-04-23 20:40 UTC, hkollmann submitted a review, later dismissed

2018-04-23 22:17 UTC, derrell requested changes
Very minor. Just a typo. Sorry.

2018-04-23 22:17 UTC, derrell commented on framework/source/class/qx/theme/manager/Decoration.js
> +        // if the docorator is not set yet, clone the topmost
if the *decorator* is not set...

2018-04-24 06:12 UTC, oetiker submitted a review, later dismissed

2018-04-24 10:48 UTC, Adolfrizer commented
You changed the order of addition properties so an operator `in` will iterate them in this order:
`local style (input-focused) -> input-base -> input`
but the correct order is:
`input-base -> input -> local style (input-focused)`
I added local style after all others

2018-04-24 11:57 UTC, level420 commented
Please do not approve currently. Still in discussion. Thank you.

2018-04-24 12:06 UTC, level420 commented
@Adolfrizer Please have again a look into the PR. I've fixed one existing problem and simplified the algorithm even more.

The "trick" is, that recursion starts with the current decorator definition, in the example `input-focused` in function `recurseDecoratorInclude` where, if an `include` property exists, it recursively calls the function with the `input` decorator which recursively calls the function with the `input-base` decorator.

As the recursion ends here, the styles get copied first over from `input-base` then from `input` and last from `input-focused`. This should be the right order, beginning from the topmost include down to the current decorator.

Additionally I've removed the unneeded clone of the `decoration` entry which seems to me to be a relic from ancient code, as not decorator entry has an attribute called `decorator`.

As only the `style` object/hash is used when creating the decorator, there is no need for `entry.styles`.

2018-04-24 12:09 UTC, level420 commented
And also note that the PR will not include the debug message anymore. This is just to illustrate that copying the styles works in the right order. 

The `name` parameter of the function `recurseDecoratorInclude` could also be used to track if we have circular references in the decorators, thus things like `dec1.include = "dec2"` and `dec2.include = "dec1"`.

2018-04-25 05:35 UTC, Adolfrizer approved these changes
I think it's OK. I verified it locally

2018-04-25 05:39 UTC, cboulanger approved these changes

2018-04-25 08:07 UTC, hkollmann approved these changes

2018-04-25 09:25 UTC, johnspackman approved these changes

2018-04-25 10:06 UTC, cajus approved these changes

2018-04-25 11:09 UTC, derrell approved these changes

2018-04-25 13:11 UTC, oetiker approved these changes

2018-04-26 11:48 UTC, merged

2018-04-26 11:48 UTC, johnspackman commented
full approval, merging thank you @level420 !

2019-12-17 21:03 UTC, hkollmann commented
@level420 @Adolfrizer : Can we close this issue?