Added File to Xhr whitelist because File inherits from Blob
qooxdoo/qooxdoo pull request #9540
Opened 2018-06-18 15:43 UTC by milandamen

See https://developer.mozilla.org/en-US/docs/Web/API/File

I've tested this with Chrome 67.0.3396.87 and Firefox 60.0.2.

2018-06-18 16:54 UTC, oetiker approved these changes
makes sense

2018-06-18 17:25 UTC, hkollmann approved these changes

2018-06-19 07:33 UTC, level420 reviewed
The comment where `this.__dataTypeWhiteList` is evaluated states that it may be that `File` is omitted in order to get par with browser functionality. If I read/interprete the code correctly if `File` is not listed in the whitelist it gets converted to string for other browsers.
@milandamen could you please also test this for IE, Edge and Safari if this works there as expected?
See https://github.com/milandamen/qooxdoo/blob/b7730516f6fd26e0bf8cf1f61f17499200f26a24/framework/source/class/qx/bom/request/Xhr.js#L425-L431

2018-06-19 07:34 UTC, level420 requested changes
See my last comment.

2018-06-19 15:43 UTC, milandamen commented
Sadly I don't have access to IE, Edge or Safari. The File API is supported by all major browsers, check out this page: https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility

When `File` is not listed in the whitelist, the only data that gets sent is the literal `[object File]` as the request body content.

2018-06-19 15:56 UTC, oetiker commented
how about checking if it exists and only add it if it does ?

2018-06-20 10:07 UTC, level420 approved these changes
After looking a bit arround I'm changing my mind and approve this.

As the whitelist only contains strings, it should work automatically even on those browsers/clients not supporting `File` at all.

The type of object instance which ist tested against the whitelist is retreived via `qx.Bootstrap.getClass(someinstance)` which should always retreive the type of the given instance on the given client and which never should be "File" if there is no "File" support.

2018-06-20 10:09 UTC, johnspackman approved these changes

2018-06-20 10:17 UTC, cboulanger approved these changes

2018-06-22 11:18 UTC, derrell approved these changes

2018-06-25 14:09 UTC, merged