make iconfonts work with latest qxcompiler in --target=build mode
qooxdoo/qooxdoo pull request #9573
Opened 2018-09-11 15:50 UTC by oetiker

It seems that something in the qxcompiler dependencies (babel?) has changed so that the large
`if else` structure in `Image.js` gets damaged in the compilation output when running in build mode. Switching to a `switch case` structure I was able to make icon fonts work again. 

As the code is much nicer like this anyway, I am submitting a patch. But as the `if else` structures do show up elsewhere in the code, further investigation into why this breaks would certainly be warranted.

2018-09-11 15:58 UTC, derrell requested changes

2018-09-11 15:58 UTC, derrell commented on framework/source/class/qx/ui/basic/Image.js
> +          tagName = "img";
Even though not strictly required here, the default block should have a trailing `break;` statement.

2018-09-11 16:03 UTC, cboulanger submitted a review, later dismissed

2018-09-11 20:04 UTC, derrell approved these changes

2018-09-12 06:56 UTC, hkollmann approved these changes

2018-09-12 08:52 UTC, level420 approved these changes

2018-09-12 08:55 UTC, cboulanger approved these changes

2018-09-12 08:58 UTC, cajus approved these changes

2018-09-12 09:06 UTC, johnspackman approved these changes

2018-09-12 11:00 UTC, johnspackman requested changes
On second thoughts, this should not be approved just for the sake of a bug in qxcompiler (especially as I think that may be fixed now).  Are there reasons *other than* https://github.com/qooxdoo/qooxdoo-compiler/issues/207 ?

2018-09-12 11:16 UTC, derrell commented
Although certainly subjective, the `switch` statement feels to me like a cleaner implementation than a long series of `if/else` statements...

2018-09-12 12:18 UTC, johnspackman commented
> Although certainly subjective, the `switch` statement feels to me like a cleaner implementation than a long series of `if/else` statements...

Fair enough, i'll remove my request for change

2018-09-12 12:18 UTC, johnspackman approved these changes

2018-09-12 13:14 UTC, merged