add support for automatic npm deploy to travis build
qooxdoo/qooxdoo pull request #9586
Opened 2018-10-28 16:44 UTC by hkollmann

2018-10-28 19:28 UTC, oetiker commented on .travis.yml
> +      name: Deploy to npm
you have to add a `- #` see above

2018-10-28 19:31 UTC, oetiker requested changes
see comment

2018-10-29 07:13 UTC, oetiker approved these changes

2018-10-29 09:58 UTC, johnspackman approved these changes

2018-10-29 11:28 UTC, derrell approved these changes

2018-11-01 17:35 UTC, cboulanger approved these changes

2018-11-07 08:00 UTC, level420 approved these changes

2018-11-07 08:03 UTC, cajus approved these changes

2018-11-12 10:53 UTC, level420 commented
full quorum. merging
thank you @hkollmann

2018-11-12 10:53 UTC, merged