Allows to customize the label suffix (default " :") and the required …
qooxdoo/qooxdoo pull request #9604
Opened 2018-12-07 21:11 UTC by cboulanger

…suffix (default: red asterisk) in the form renderer by refining the values of two new properties.

This time, without the merge commits!

2018-12-07 22:58 UTC, oetiker submitted a review, later dismissed
great ... that one has been bothering me too :)

2018-12-07 23:04 UTC, hkollmann submitted a review, later dismissed

2018-12-08 21:11 UTC, derrell requested changes

2018-12-08 21:11 UTC, derrell commented on framework/source/class/qx/ui/form/renderer/AbstractRenderer.js
> +       * A string that is appended to the label if it is not empty
This documentation string is the same as the one above. Both properties have a bit more (and different) detail about what the property actually does.

2018-12-09 14:31 UTC, derrell approved these changes

2018-12-09 19:14 UTC, hkollmann approved these changes

2018-12-09 20:37 UTC, level420 approved these changes

2018-12-11 11:01 UTC, oetiker approved these changes

2018-12-11 11:26 UTC, johnspackman approved these changes

2018-12-11 12:03 UTC, cajus approved these changes

2018-12-11 13:26 UTC, merged