Add support for hi-res images to AbstractImage cellrenderer
qooxdoo/qooxdoo pull request #9625
Opened 2019-02-06 19:47 UTC by hkollmann

Based on https://github.com/qooxdoo/qooxdoo/pull/9610. Moved findHigh… ResolutionSource and _getHighResolutionSource to qx.util.ResourceManager.

2019-02-06 19:56 UTC, johnspackman requested changes

2019-02-06 19:56 UTC, johnspackman commented on framework/source/class/qx/ui/basic/Image.js
> +        var highResolutionSource = qx.util.ResourceManager.getInstance().findHighResolutionSource(source);
`qx.util.ResourceManager.getInstance()` has already been saved as `ResourceManager`, maybe shorten it here

2019-02-06 19:56 UTC, johnspackman commented on framework/source/class/qx/ui/mobile/basic/Image.js
> +          var highResSource = qx.util.ResourceManager.getInstance().findHighResolutionSource(source, qx.ui.mobile.basic.Image.ROOT.getAppScale());
also `resourceManager` here

2019-02-07 06:09 UTC, level420 approved these changes

2019-02-07 07:21 UTC, oetiker approved these changes

2019-02-07 07:34 UTC, cboulanger approved these changes

2019-02-07 07:51 UTC, johnspackman approved these changes

2019-02-10 15:42 UTC, oetiker approved these changes

2019-02-10 17:13 UTC, derrell approved these changes

2019-02-15 19:41 UTC, level420 commented
plenty of days passed. 5 approvals. merging.
thank you @hkollmann

2019-02-15 19:41 UTC, merged

2019-03-25 12:27 UTC, oetiker commented on framework/source/class/qx/ui/table/cellrenderer/AbstractImage.js
> +          "background-size": backgroundSize,
that seems odd ... decorations would normally use camel case

2019-03-25 14:45 UTC, oetiker commented on framework/source/class/qx/ui/table/cellrenderer/AbstractImage.js
> +      var backgroundSize = this.__imageData.width + "px, " + this.__imageData.height + "px";
background-size has no comma: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size #9646