Consistent behaviour for keypress events in general and firefox version 65
qooxdoo/qooxdoo pull request #9629
Opened 2019-02-15 14:50 UTC by level420

To have a consistent behaviour between browsers, we need to also fire artificial keypress events when the meta keys are pressed, except the SHIFT key.
Also fire artificial keypress events for keys BACKSPACE, TAB and ESCAPE for gecko/firefox version 65 and up.

See #9626 #9623

2019-02-15 14:54 UTC, cboulanger submitted a review, later dismissed

2019-02-15 14:56 UTC, derrell requested changes

2019-02-15 14:56 UTC, derrell commented on framework/source/class/qx/event/handler/Keyboard.js
> +              domEvent.ctrlKey || domEvent.altKey || domEvent.metaKey) {
This concept looks good. Please, however, don't insert comments right in the middle of an expression. That makes the code difficult to read. I'd suggest something like the following, inserted at line 349, and move that comment to before line 349:
```
let isModified = domEvent.ctrlKey || domEvent.altKey || domEvent.metaKey);
```

(And then, of course, change the `if` statement to use `isModified`)

2019-02-15 15:39 UTC, level420 commented
FYI: the fix needed for `qx.ui.table.Table` here https://github.com/qooxdoo/qooxdoo/pull/216 would not have been necessary if we had this fix.

The problem there was, that at some point chrome did not fire a keypress event anymore if you had hold down the `CTRL` key. This resulted in the `CTRL` key being detected, but not the `A` key afterward.
With this fix you get first a `keypress` event for the `CTRL` key and then a `keypress` for the `A` key.

2019-02-15 16:06 UTC, derrell approved these changes

2019-02-15 16:16 UTC, johnspackman approved these changes

2019-02-15 16:18 UTC, cboulanger approved these changes

2019-02-15 21:02 UTC, hkollmann approved these changes

2019-02-17 16:56 UTC, oetiker approved these changes

2019-02-20 15:25 UTC, merged