This adds an emergy hotfix rule to the pullapprove rules
qooxdoo/qooxdoo pull request #9696
Opened 2019-06-11 19:31 UTC by cboulanger

and also fixes a bug in the rules

2019-06-11 19:37 UTC, hkollmann submitted a review, later dismissed

2019-06-11 19:41 UTC, derrell requested changes

2019-06-11 19:41 UTC, derrell commented on .pullapprove.yml
> +      request: 2  # 2 review request will be sent at a time
The request should be sent to everyone, but require only 2 approvals.

2019-06-12 07:38 UTC, hkollmann approved these changes

2019-06-12 09:37 UTC, johnspackman approved these changes

2019-06-12 11:24 UTC, level420 approved these changes

2019-06-12 11:42 UTC, derrell approved these changes

2019-06-12 20:48 UTC, oetiker approved these changes

2019-06-12 20:58 UTC, merged