[travis-docs-only] adds documentation for https://github.com/qooxdoo/qooxdoo-compiler/pull/448
qooxdoo/qooxdoo pull request #9701
Opened 2019-06-15 14:52 UTC by johnspackman

2019-06-15 19:30 UTC, hkollmann requested changes
We should have an hint that this is just an example! Sass is working out of the box in current Compiler so this is not needed  for mobile apps!

2019-06-15 22:57 UTC, oetiker approved these changes

2019-06-16 09:39 UTC, johnspackman commented
@hkollmann it says that this is a "working example" three times and also that it is "meant as an example only" ...  I'll make it clear that sass is already working.

2019-06-16 11:30 UTC, hkollmann approved these changes

2019-06-16 13:16 UTC, cboulanger commented
Tests fail because my documentation PR needs to be merged first which fixes most dead internal links: https://github.com/qooxdoo/qooxdoo/pull/9700.
BTW, `[travis-docs-only]` is no longer necessary, it will automatically detect PRs that commit only to `docs/*`

2019-06-16 16:21 UTC, derrell approved these changes

2019-06-17 10:26 UTC, merged