let index.html show to qooxdoo repos
qooxdoo/qooxdoo pull request #9703
Opened 2019-06-16 14:59 UTC by hkollmann

2019-06-16 15:36 UTC, cboulanger approved these changes

2019-06-16 16:25 UTC, derrell approved these changes

2019-06-16 16:37 UTC, level420 approved these changes

2019-06-16 18:19 UTC, johnspackman requested changes

2019-06-16 18:19 UTC, johnspackman commented on docs/index.html
> +>>>>>>> master
still has git merge artifacts

2019-06-16 20:12 UTC, hkollmann commented on docs/index.html
> +>>>>>>> master
Thanks for the hint. Fixed now

2019-06-17 05:56 UTC, oetiker approved these changes

2019-06-17 09:20 UTC, johnspackman approved these changes

2019-06-17 14:35 UTC, merged