Replace xml-based variable file with json-based one
qooxdoo/qooxdoo pull request #9728
Opened 2019-07-01 11:05 UTC by cboulanger

2019-07-01 11:16 UTC, oetiker approved these changes
YES :-)

2019-07-01 11:50 UTC, hkollmann requested changes
You should change tool/admin/bin/bumpqxversion.py to change the version in variables.json too!
Then the version changed is done automatically during publish.

2019-07-01 12:05 UTC, hkollmann approved these changes

2019-07-01 14:58 UTC, derrell approved these changes

2019-07-01 20:03 UTC, zaucker approved these changes

2019-07-02 15:26 UTC, johnspackman approved these changes

2019-07-02 15:27 UTC, merged

2019-07-02 15:27 UTC, johnspackman commented
full quorum, thank you @cboulanger