Native Snap for Chrome and Safari (#9593)
qooxdoo/qooxdoo pull request #9836
Opened 2019-12-22 07:34 UTC by johannes-nivus

This is my first PR ever. And also the first time I tried to work with github. So please be patient.

Summary:
Use Native Snap where possible (Chrome and Safari)
Changed Snap boundaries to middle of previous element, because of Chrome snapping native to fractions of a pixel which leads to setting the value to the wrong element in a picker.
Todo:
Improve the browser conditionals (Perhaps include Versions etc.):
I haven't found a definite way how to do this throughout the code, feel free to point me in the right directions.

2019-12-22 16:25 UTC, hkollmann commented
Many thanks for your first PR! Great!

With https://caniuse.com/#search=scroll-snap scroll-snap-type is supported in all modern browsers.
So what do you think about testing the support like suggested here:
https://stackoverflow.com/questions/33615761/js-check-if-browser-supports-css-snap-points

if ("scroll-snap-type" in document.body.style) {
    // do stuff with `scroll-snap-points`
  } else {
    // `scroll-snap-points` not supported
  }

2019-12-22 16:34 UTC, hkollmann commented
Qooxdoo style for the test would be to add an static method to qx.bom.client.Css and add an new enviroment variable at the end of the file in the defer section.

This could be used in your code then.

2019-12-22 17:49 UTC, oetiker approved these changes

2019-12-22 17:55 UTC, oetiker requested changes

2019-12-22 17:55 UTC, oetiker commented on framework/source/class/qx/ui/mobile/container/MNativeScroll.js
> +         qx.core.Environment.get("browser.name").indexOf("safari") == -1) {
don't repeat yourself

2019-12-22 17:55 UTC, oetiker commented on framework/source/class/qx/ui/mobile/container/MNativeScroll.js
> +         qx.core.Environment.get("browser.name").indexOf("safari") == -1) {
this seems a rather odd way of checking the browser ... also a feature test would be preferred

2019-12-22 17:55 UTC, oetiker commented on framework/source/class/qx/ui/mobile/container/MNativeScroll.js
> +             qx.core.Environment.get("browser.name").indexOf("safari") == -1) {
DRY

2019-12-22 18:08 UTC, johannes-nivus commented
@oetiker, @hkollmann 
I will implement a feature test and use a corresponding environment variable.
But just a short question: How do I change a PR? Just editing my fork? Close and recommit?

2019-12-22 18:29 UTC, hkollmann commented
Just commit to your fork and branch. The rest is done by github

2019-12-22 18:31 UTC, hkollmann commented
BTW to held your master branch clean it's easier to create a branch before committing.

2021-02-08 08:52 UTC, cboulanger commented
@johannes-nivus We're closing this PR because it is incompatible with current (v7) master. Since we're interested in what the PR is trying to achieve, we would like to ask you to open an new one shoud you upgrade to current master for your development (one major change is that `/framework/source` has been moved to `/source`). Thank you.

2021-02-08 08:52 UTC, closed without merging