fix for Issue #9627
qooxdoo/qooxdoo pull request #9841
Opened 2019-12-28 16:26 UTC by hkollmann

store listener unique ids added in addListenerOnce 
store listener unique ids added in addListenerOnce to remove all listeners correctly.

Bug in MEvent.addListenerOnce() for multiple times call with same args qooxdoo#9627

Taken from https://github.com/fortooon/qooxdoo/pull/2/commits/0ddde1efeedf721881e1466b715cd0b48f16cbd6

2019-12-28 16:35 UTC, cboulanger approved these changes

2019-12-30 15:10 UTC, oetiker approved these changes

2019-12-30 15:35 UTC, derrell requested changes
see inline comment

2019-12-31 17:48 UTC, hkollmann commented on framework/source/class/qx/core/MEvent.js
> +          qx.lang.Array.removeAt(listener.$$wrapped_callbacks_ids[type + this.$$hash], i);
Good idea! Next year …

2020-01-02 15:59 UTC, derrell approved these changes

2020-01-03 12:44 UTC, hkollmann commented
found a much simpler solution

2020-01-03 12:44 UTC, closed without merging