#9859 fixed wrong column width calculation with colSpan
qooxdoo/qooxdoo pull request #9860
Opened 2020-02-11 09:30 UTC by Holdwyn

I've adopted the existing solution for rowHeights with rowSpan.

2020-02-11 10:09 UTC, oetiker commented
are there no tests for the grid layout?

2020-02-11 10:55 UTC, Holdwyn commented
> are there no tests for the grid layout?

of corse there are ... I've added a test case

2020-02-11 12:34 UTC, oetiker commented on framework/source/class/qx/test/ui/layout/Grid.js
> +
```suggestion
      this.flush();
      this.assertEquals(200, this._gridWidget.bounds.width);
```

an this too ?

2020-02-11 22:14 UTC, derrell requested changes
Just one typo. Looks good, I think. Thanks.

2020-02-11 22:14 UTC, derrell commented on framework/source/class/qx/ui/layout/Grid.js
> +            // get the col height which every child would need to share the
get the col **width**?

2020-02-12 10:23 UTC, hkollmann approved these changes

2020-02-12 12:17 UTC, cboulanger approved these changes

2020-02-12 14:48 UTC, derrell approved these changes

2020-02-19 12:32 UTC, oetiker approved these changes

2020-02-20 10:14 UTC, level420 approved these changes

2020-02-20 10:16 UTC, level420 commented
5 approvals, merging, thank you @Holdwyn

2020-02-20 10:16 UTC, merged