Remove deploy-to-website job
qooxdoo/qooxdoo pull request #9949
Opened 2020-05-05 13:33 UTC by cboulanger

It is no longer required since we are not updating the old website any more.  Deployment of new website can be found here: https://github.com/qooxdoo/website/blob/master/.github/workflows/deploy_website.yml

2020-05-05 13:46 UTC, derrell approved these changes

2020-05-05 13:59 UTC, level420 approved these changes

2020-05-05 14:01 UTC, johnspackman approved these changes

2020-05-05 15:56 UTC, hkollmann requested changes
What's with the building of the apps for the doc folder which is done in .travis/build-site-v6 during deploy_website? 

We should setup a github action for this.

```
# global /docs shows documentation of current master
rm -f docs                              
ln -s $(cat ../version.txt)/docs docs
# global /apps shows apps of current master, needed for /docs
rm -f apps                             
ln -s $(cat ../version.txt)/apps apps
```
links for doc and apps are build during the deploy job either.

2020-05-06 12:02 UTC, oetiker approved these changes

2020-05-06 12:30 UTC, hkollmann approved these changes
Is a must have with the new toolchain

2020-05-06 12:40 UTC, merged

2020-05-06 12:40 UTC, cboulanger commented
Full quorum, merging this despite failing tests (this is one attempt to make them pass)