Deploy docs to new website
qooxdoo/qooxdoo pull request #9952
Opened 2020-05-05 18:16 UTC by johnspackman

2020-05-05 18:41 UTC, derrell approved these changes

2020-05-05 19:15 UTC, cboulanger approved these changes

2020-05-05 19:41 UTC, hkollmann approved these changes
I would prefer a GitHub Action based new soloution.
This should be just a quick hack

2020-05-05 22:02 UTC, cboulanger requested changes
Thinking about it, let's not use the travis workflow anymore and create a dedicated github action workflow instead . See #9953

2020-05-06 12:00 UTC, oetiker requested changes

2020-05-06 12:00 UTC, oetiker commented on .travis/deploy_website
> +GIT_IO_URL="https://$GH_TOKEN@github.com/qooxdoo/website.io.git"
that seems odd ... 

```suggestion
GIT_IO_URL="https://$GH_TOKEN@github.com/qooxdoo/website.git"
```

2020-05-06 12:20 UTC, cboulanger commented
I think this PR is moot because we use a github workflow now. Can we close @johnspackman ?

2020-05-06 12:54 UTC, closed without merging