Basic tree node label editing
qooxdoo/qooxdoo pull request #9978
Opened 2020-05-19 07:50 UTC by rad-pat

I've had the need to edit the nodes in a tree and wondered if this might be useful to have as an option in the main source. It seemed that the basic edit wasn't too much trouble so I wondered why it was not included in the first instance? Perhaps there wasn't the requirement. The node editor works ok as a cell editor, but could do with being aligned with the node in the tree and I wasn't sure of the best way to go about that. Any pointers would be really helpful and I'll get this fixed up.

2020-05-19 08:27 UTC, cboulanger commented
This would be a great addition to the core. We just have to make sure that it doesn't break anything. Unfortunately, ther are no tests in the framework that test the behavior of the TreeVirtual widget, but could you maybe add a test case to https://github.com/qooxdoo/qxl.demobrowser/tree/master/source/demo/treevirtual using your fork, which could then be added to the demobrowser once the PR has been accepted?

2020-05-19 08:28 UTC, cboulanger commented
I'll try to test the PR branch with my app in the next few days to see how it works.

2020-05-19 09:13 UTC, rad-pat commented
Thanks for looking, yep I'll add some demo code

2020-05-19 10:58 UTC, derrell requested changes
This looks like a good addition.

2020-05-19 10:58 UTC, derrell commented on framework/source/class/qx/ui/treevirtual/SimpleTreeDataModel.js
>        // The tree column is not editable
This comment is no longer accurate, it seems.

2020-05-19 10:58 UTC, derrell commented on framework/source/class/qx/ui/treevirtual/celleditor/NodeEditor.js
> +      if (cellInfo.value === null || cellInfo.value === undefined) {
If `cellInfo.value` is required to be an object, as indicated by the value set below, then this test might better be
```
if (cellInfo.value === null || typeof cellInfo.value != "object")
```

2020-05-20 14:47 UTC, derrell approved these changes

2020-05-22 14:58 UTC, level420 approved these changes

2020-05-26 07:07 UTC, johnspackman approved these changes

2020-05-27 13:34 UTC, cboulanger approved these changes
Couldn't test it yet, but it looks good to me.

2020-06-01 15:50 UTC, hkollmann approved these changes

2020-06-01 16:12 UTC, merged

2020-06-01 16:12 UTC, cboulanger commented
Thank you @rad-pat for this addition!